### ISSUE TITLE
Tensor.ceil() turns 1.0 into 2

### ISSUE THREAD

**Issue by geohotstan** [geohot/tinygrad#1038]
Needed Tensor.ceil() in some onnx tests but encountered problems.

`In [33]: Tensor([1.0, 2.0, 1.1]).ceil().numpy()`
`Out[33]: array([2., 3., 2.], dtype=float32)`

I'm not sure if this is expected behavior.
😟

**Comment by geohot** [comment]
It's not, shouldn't be hard to fix.

**Comment by dee7ine** [comment]
If I understand correctly in case of whole numbers this method should should return just a number without rounding. But in current implementation if the number is greater than 0, it will always be rounded up. 
` # ***** math functions (unary) *****
  def ceil(self: Tensor) -> Tensor:
    b = self.cast(dtypes.int32).contiguous()
    return (self > 0).where(b+1, b)`

**Comment by geohotstan** [comment]
Thanks Jacky 😄
