### ISSUE TITLE
float64 unsupported on many integrated GPUs

### ISSUE THREAD

**Issue by danielbarter** [geohot/tinygrad#1087]
Hey there!

OpenCL implementations for lots of integrated GPUs do not support float64. If you have a pyopencl context, it is easy to check if there is support:

```
import pyopencl as cl
from pyopencl.characterize import has_double_support

ctx = cl.create_some_context()
opencl_float64_support = all(has_double_support(dev) for dev in ctx.devices)
```

Hopefully no one is trying to do float64 inference on a phone, but explicitly checking for support would allow for more graceful failure + skipping `TestFloat64DType` when appropriate. I am new to the project, so isn't clear to me if something like this would be useful / where it would best fit

**Comment by geohot** [comment]
I hate float64. We should just rip it out.

**Comment by wozeparrot** [comment]
Pretty sure float64 was only added for onnx tests, should be fine if we just skip those tests.

**Comment by danielbarter** [comment]
Looks like @rezaarezvan beat me to it! Closing since this is now resolved.
