### ISSUE TITLE
We have to lose 4 lines!

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#112]
Quality refactors only please.

**Comment by adamritter** [comment]
Just as an idea, the 3 conv kernels don't look that different (1 forward and 2 backward passes). There should be a way to use less.

**Comment by marcelbischoff** [comment]
There are 3-4 lines of just comments in the conv kernels.

**Comment by adamritter** [comment]
Sure, but just taking them out doesn’t make the code more readable (high
quality refactor).

Marcel Bischoff <notifications@github.com> (időpont: 2020. nov. 12., Cs,
20:34) ezt írta:

**Comment by geohot** [comment]
Yea, I feel like we should be able to share two of the conv kernels.
