### ISSUE TITLE
Stable Diffusion results in Terminated

### ISSUE THREAD

**Issue by iJustErikk** [geohot/tinygrad#1123]
On GitHub Codespaces, running stable diffusion results in "Terminated".

Steps to reproduce:

- run install
- run stable diffusion

I am debugging this- it seems the issue is with the first SpatialTransformer inside of the UNet.

**Comment by iJustErikk** [comment]
The issue (at least the main one) is not with the SpatialTransformer. It is when we realize the output tensor

**Comment by geohot** [comment]
Out of memory?

**Comment by iJustErikk** [comment]
Yeah it was. Was running stable diffusion on 8gb machine. Lemme close this
