### ISSUE TITLE
Error while trying to run examples/efficientnet.py

### ISSUE THREAD

**Issue by linuzo** [geohot/tinygrad#124]
Traceback (most recent call last):
  File "examples/efficientnet.py", line 14, in <module>
    from extra.efficientnet import EfficientNet
ModuleNotFoundError: No module named 'extra.efficientnet'

How do I get module 'extra.efficientnet'??

**Comment by marcelbischoff** [comment]
That is a path issue. For me it works with `ipython3 examples/efficientnet.py https://upload.wikimedia.org/wikipedia/commons/4/41/Chicken.jpg`

**Comment by linuzo** [comment]
Thanks so much..  installed ipython and working :+1:  Noob here just trying to play around and learn about Neuralnets
