### ISSUE TITLE
Design custom FOSSi hardware, get it printed for free

### ISSUE THREAD

**Issue by tsmcalister** [geohot/tinygrad#129]
The project is at nearly 1000 stars so it's clearly time to start thinking about custom hardware.
Could be designed in the open and then [manufactured for free.](https://fossi-foundation.org/2020/06/30/skywater-pdk)

@geohot I think it makes sense to tag this as a good first issue.

**Comment by adamritter** [comment]
This is great idea, it should be on the TSMC 5nm process. Could you make a
fork, design it, send the ASIC design to TSMC and when it's back create a
pull request?

**Comment by adamritter** [comment]
I'll try to be a bit more constructive: it would probably be a fun project
to create an FPGA based backend for the operations, but that should be a
separate project. Also this is a fun learning experience for us, and maybe
you are looking for something more productionized.

**Comment by geohot** [comment]
Sounds fun, though 130nm wouldn't be close to competitive with anything.

**Comment by tsmcalister** [comment]
True, it was also more of a joke. So I'm closing now :)
