### ISSUE TITLE
why not directly expose elements under the modules of tinygrad in __init__.py

### ISSUE THREAD

**Issue by PatxiofromAlphensign** [geohot/tinygrad#135]
in `tinygrad/__init__.py`, the modules are exposed like :
```python
import tinygrad.nn
import tinygrad.xxx
```
Why not expose the modules as by their name directly, for example

```python
from tinygrad import nn

```
or
```python
from tinygrad.nn as nn

```

**Comment by thangtran480** [comment]
i think it's not a problem, just about personal code conventions.

**Comment by PatxiofromAlphensign** [comment]
then I think, the former makes `__init__.py` kinda useless

**Comment by Liamdoult** [comment]
@PatxiofromAlphensign Its probably just bloat, perhaps you would like to make a PR to remove it? It might help with #94

**Comment by geohot** [comment]
Yea I don't really understand init files, I'd merge a good PR that explains it to me and keeps the examples working.

Like
```
from tinygrad.tensor import Tensor
```
should still work

**Comment by PatxiofromAlphensign** [comment]
Oops my bad, the examples I showed are just redundant bloat and yeah you got it right 

```python

from tinygrad.<module> import <class> 

```
Makes the objects under `tinygrad/*.py' directly exposed making the user use 

```python

from tinygrad import tensor 

```
