### ISSUE TITLE
No module named 'tinygrad' when running test from terminal.

### ISSUE THREAD

**Issue by skoshx** [geohot/tinygrad#142]
Running the command:
```shell
$ python3.8 test/test_mnist.py TestMNIST.test_sgd_gpu
```

Outputs following error:
```
Traceback (most recent call last):
  File "test/test_mnist.py", line 5, in <module>
    from tinygrad.tensor import Tensor, GPU
ModuleNotFoundError: No module named 'tinygrad'
```

This is the result of importing in the following manner
```python
from tinygrad.tensor import Tensor, GPU                                         
from tinygrad.utils import layer_init_uniform, fetch
```

Shouldn't we use relative path imports here instead? Shouldn't the code be able to run without installing with:

`pip3 install git+https://github.com/geohot/tinygrad.git --upgrade`

**Comment by marcelbischoff** [comment]
Either use `ipython3` or `PYTHONPATH=. python3.8 test/test_mnist.py TestMNIST.test_sgd_gpu`

**Comment by skoshx** [comment]
Oh ok, thanks a lot! Didn't know about the `PYTHONPATH`env variable... Closing...
