### ISSUE TITLE
EfficientNet runs slower on GPU than CPU

### ISSUE THREAD

**Issue by skoshx** [geohot/tinygrad#144]
Running EfficientNet in `examples/efficientnet.py` runs slower on the GPU than CPU for some reason. Benchmarks:

`PYTHONPATH=. GPU=1 python3.8 examples/efficientnet.py  https://image.shutterstock.com/image-illustration/compact-white-car-3d-render-260nw-405716083.jpg`
Output (GPU):
```
656 7.561172 minivan
did inference in 1.13 s
``` 

`PYTHONPATH=. python3.8 examples/efficientnet.py  https://image.shutterstock.com/image-illustration/compact-white-car-3d-render-260nw-405716083.jpg`
Output (CPU):
```
656 7.5611706 minivan
did inference in 0.71 s
```

What could be causing this? Im runninng this with Python 3.8 on a MacBook Pro 2018 with Intel Iris Plus Graphics 1536 MB running macOS Catalina.

**Comment by geohot** [comment]
You can profile with DEBUG=1, see what is slow. Low end GPUs aren't always faster, especially with our fairly untuned CL kernels.

**Comment by skoshx** [comment]
Profiling results from CPU:
```
817 10.583674 sports car, sport car
did inference in 0.80 s
              Conv2D :  81      333.68 ms
             Sigmoid :  65      168.89 ms
                 Pow :  98      103.23 ms
                 Mul : 163       44.68 ms
           AvgPool2D :  17       30.87 ms
                 Add : 140       16.98 ms
               Pad2D :  17       13.13 ms
                 Sub :  49        8.62 ms
             Reshape : 230        2.05 ms
                 Dot :   1        1.53 ms
```

Seems reasonable, Convolution and sigmoid take the most time. Here is where it gets interesting; Mul operations only take 44ms. Now look at the GPU results:

```
817 10.583665 sports car, sport car
did inference in 0.98 s
                 Mul : 163      262.09 ms
                 Add : 140      121.99 ms
                 Pow :  98       89.23 ms
                 Sub :  49       76.33 ms
             Reshape : 230       70.66 ms
               Pad2D :  17       25.45 ms
              Conv2D :  81       17.54 ms
             Sigmoid :  65       16.92 ms
           AvgPool2D :  17       16.47 ms
                 Dot :   1        6.95 ms
```
Conv2D layer is fast, same with sigmoid activation, but Mul operations take 262 ms instead of 44ms! Should the Mul operations be performed in the CPU or the OpenCL Kernel code optimized? Or am I the only one having insanely high Mul operation times?

**Comment by geohot** [comment]
So it's not that, the profiler is bad. That's just the time spent enqueuing the ops, finish isn't called until the end. Make sure you are on master, there's been an improvement here.

**Comment by skoshx** [comment]
Ran same tests on master, there is improvement, however the same operations (Mul, Add, Sub, Reshape, Pad2D) perform noticably worse on GPU than on CPU.

Is it a matter of optimizing the OpenCL kernel code or is it the global memory access (broadcasting) that bottlenecks the operations?

**Comment by geohot** [comment]
This is the real timing after adding queue finish.

```
did inference in 0.61 s
              Conv2D :     81     202.97 ms
                 Mul :    163      97.18 ms
                 Add :    140      77.28 ms
                 Pow :     98      68.10 ms
                 Sub :     49      42.52 ms
             Sigmoid :     65      21.67 ms
               Pad2D :     17      18.95 ms
           AvgPool2D :     17      15.58 ms
             Reshape :    230       7.50 ms
                 Dot :      1       3.66 ms
```

**Comment by skoshx** [comment]
This is the output of the profiler running EfficientNet on GPU:
```
did inference in 1.72 s
              Conv2D :     81     391.03 ms
                 Mul :    163     390.37 ms
                 Add :    140     235.93 ms
                 Sub :     49     162.44 ms
               Pad2D :     17     142.51 ms
                 Pow :     98      94.95 ms
             Sigmoid :     65      62.24 ms
           AvgPool2D :     17      51.74 ms
                 Dot :      1      46.15 ms
             Reshape :    230      22.35 ms
```
This is the same on CPU:
```
did inference in 0.65 s
              Conv2D :     81     312.13 ms
             Sigmoid :     65     171.63 ms
                 Mul :    163      35.57 ms
           AvgPool2D :     17      27.39 ms
               Pad2D :     17      16.41 ms
                 Add :    140      16.40 ms
                 Sub :     49       8.07 ms
             Reshape :    230       1.97 ms
                 Pow :     98       1.91 ms
                 Dot :      1       1.25 ms
```

So it seems like the CPU performance improved, but GPU performance decreased? This is on `master`. Am I the only one getting times like this on MacBook Intel GPUs? Will be investigating and benchmarking further…

**Comment by geohot** [comment]
Be careful, it might be using the CPU OpenCL. Set interactive=true to pick

**Comment by skoshx** [comment]
@geohot 
Yes, turns out it was using the CPU:
```
<pyopencl.Context at 0x7ff018b0d4f0 on <pyopencl.Device 'Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz' on 'Apple' at 0xffffffff>>
760 9.321052 refrigerator, icebox
did inference in 0.81 s
```

I added the following code in `require_init_gpu()` to ONLY pick GPU devices if GPU=1 is defined:
```python
gpus = cl.get_platforms()[0].get_devices(device_type=cl.device_type.GPU)
cl_ctx = cl.Context(devices=gpus)
```

This picks the Intel Iris GPU for all the computations, however, the results are still underwhelming:
```
760 9.321049 refrigerator, icebox
did inference in 1.00 s
              Conv2D :     81     238.86 ms
                 Mul :    163     185.37 ms
                 Add :    140     139.44 ms
                 Sub :     49      75.34 ms
                 Pow :     98      73.51 ms
               Pad2D :     17      60.47 ms
             Sigmoid :     65      43.23 ms
           AvgPool2D :     17      31.62 ms
             Reshape :    230      20.97 ms
                 Dot :      1       4.40 ms
```

CPU still outperforms the GPU because of the slow time performance of the binary operations. Is there any work being done to optimize the binary ops on GPU? I would gladly work on optmizing them, just need some direction to start looking.

Also, should I submit a pull request with the change to `require_init_gpu()`?

**Comment by geohot** [comment]
I'd merge a request to do GPU first than CPU, but we need CPU for CI.

The broadcast binary code is terribly slow. I'd start there.

**Comment by skoshx** [comment]
#180 

This pull request selects available GPU devices, and falls back to CPU if none are available. Do tell, if any changes need to be made. Also, now GPU code runs approximately 2x faster than CPU on my device, great seeing such progress from every contribution!
