### ISSUE TITLE
Support multiplying by numbers

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#149]
Create the unit tensor right before the forward pass

https://github.com/geohot/tinygrad/blob/0cf21881b710dd55614a1eb19c5ca0e7081cb8b5/tinygrad/tensor.py#L215

**Comment by kartik4949** [comment]
@geohot 
had to write this chaining statement due to no number conversion support :P
will file a pr :)

**Comment by marcelbischoff** [comment]
should we make multiplication by a scalar an elementary operation?

**Comment by kartik4949** [comment]
```
def Mul(Function):
   def forward(ctx, x, y):
         if not isinstance(y, Tensor):
            y = Tensor(y)
```
works? @geohot

**Comment by marcelbischoff** [comment]
you will need `requires_grad = False` and also free it?

**Comment by kartik4949** [comment]
> you will need `requires_grad = False` and also free it?

well yeah.
