### ISSUE TITLE
Can we beat...

### ISSUE THREAD

**Issue by marcelbischoff** [geohot/tinygrad#157]
... or at least replicate https://github.com/Matuzas77/MNIST-0.17 with tinygrad? I think we have all the ops (besides augmentation).

**Comment by kartik4949** [comment]
I guess so because there is no computational constraints
augmentations will make with ops

**Comment by geohot** [comment]
That's a good test for BatchNorm

**Comment by kartik4949** [comment]
@geohot i have wrote a full image processing library 
@geohot 
https://www.github.com/kartik4949/TensorPipe

**Comment by marcelbischoff** [comment]
Got it roughly working. We don't have padding and don't have `abs` for $$\ell^1$$-regularization.

**Comment by geohot** [comment]
Haha, I wrote it too. Under examples/serious_mnist.py

It's so slow!

**Comment by geohot** [comment]
If you want to merge the two I'll merge into serious_mnist. We still need to fix BatchNorm upstream.

**Comment by marcelbischoff** [comment]
I wrote the squeeze etc and it trains. I can merge it tomorrow. Will run it overnight ;)

**Comment by marcelbischoff** [comment]
I got 99.43% that the original model gets around 99.6 in a single run and 99.84% ensembling 20 models. We need faster Conv's so that doesn't take hours per epoch!
