### ISSUE TITLE
simple GAN to generate mnist data :).

### ISSUE THREAD

**Issue by kartik4949** [geohot/tinygrad#161]
I have some progress in simple GAN with tinygrad.
fixin' batchnorm in personal fork.
@geohot suggestions

**Comment by skoshx** [comment]
@kartik4949 Sounds really interesting! Will be looking into your fork once I figure out why tinygrad runs slower on GPU than on CPU 👍 Was also thinking about getting GANs working on tinygrad. Eventually a language model would also be amazing.

**Comment by kartik4949** [comment]
@skoshx sure , my guess is binary_op need optimization.

**Comment by kartik4949** [comment]
Done !!
