### ISSUE TITLE
Can not install on Google Collab

### ISSUE THREAD

**Issue by martasp** [geohot/tinygrad#185]
Cant install on Google collab:

!pip3 install git+https://github.com/geohot/tinygrad.git --upgrade

[2]
!pip3 install git+https://github.com/geohot/tinygrad.git --upgrade
Collecting git+https://github.com/geohot/tinygrad.git
  Cloning https://github.com/geohot/tinygrad.git to /tmp/pip-req-build-l8hpztzx
  Running command git clone -q https://github.com/geohot/tinygrad.git /tmp/pip-req-build-l8hpztzx
ERROR: Package 'tinygrad' requires a different Python: 3.6.9 not in '>=3.8'

![image](https://user-images.githubusercontent.com/13511209/101992168-ded43e80-3cb9-11eb-85af-eaed152280c3.png)

**Comment by geohot** [comment]
tinygrad requires Python 3.8 because the walrus operator is awesome, maybe there's a flag for colab?

**Comment by marcelbischoff** [comment]
```
!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh
!chmod +x mini.sh
!bash ./mini.sh -b -f -p /usr/local
!conda install -q -y --prefix /usr/local jupyter
!python -m ipykernel install --name "py38" --user
!pip install kora
import kora.install.py38
```
