### ISSUE TITLE
Indentation linter does not work...

### ISSUE THREAD

**Issue by Liamdoult** [geohot/tinygrad#198]
This passed indentation checks lol
``` python
  elif device == Device.ANE:
   require_init_ane()
   with ProfileOp("toANE", [data]):
       ndata = ane.tensor(data.shape)
       ndata.data()[:] = data
       return ndata
```
That includes the 1 space indent.

**Comment by gamwe6** [comment]
Pylint should throw an "unexpected indent" error,
```yaml
- name: Validate indentation is 2 lines
  run: if [[ $(pylint --jobs=0 --indent-string='  ' * | grep "Bad indentation") ]]; then exit 1; fi
```
but it looks like the test is only checking if the response contains "Bad indentation", which is the case here.

What do you suggest?

**Comment by Liamdoult** [comment]
I am not sure if that is the reason the test is not working correctly. If I run the script locally it correctly reports failed:
``` bash
 % if [[ $(pylint --jobs=0 --indent-string='  ' examples | grep "Bad indentation") ]]; then echo "failed"; fi
failed
```

But I would probably remove the bash `if` in favor of `pylint`:
``` bash
pylint --disable=all -e W0311 --jobs=0 --indent-string='  ' *
```

**Comment by Liamdoult** [comment]
PS, a PR that fixes this issue SHOULD fail until all the indentation issues are fixed.

**Comment by gamwe6** [comment]
I guess I didn't understand the initial issue. Indeed relying directly on `pylint` is much better.
Side note: instead of using the code `W0311`, I would rather use the more explicit version `--enable=bad-indentation`.
