### ISSUE TITLE
Running tinygrad on an iPad (example)

### ISSUE THREAD

**Issue by nmilosev** [geohot/tinygrad#199]
Hey @geohot  and everyone, big fan of your work here.

Yesterday night I managed to run `tinygrad` on my old ipad, just for fun, inside the Carnets app. Everything seems to work great, here are some screenshots attached. I managed to even train with MNIST (both the fcn and cnn). It is fast enough, around 90 seconds to train and test. Maybe this can be useful for someone, who wants to play with it. :)

The installation is a little bit tricky, here is how I did it: https://gist.github.com/nmilosev/0b6e9600bf0a4b0a16b19ce9d8da12b2

![image1](https://user-images.githubusercontent.com/11432491/102243302-4cbb7880-3efb-11eb-979a-ca14efd99f3f.png)

![image0](https://user-images.githubusercontent.com/11432491/102243308-4e853c00-3efb-11eb-8a5d-df677b1de3d4.png)

**Comment by geohot** [comment]
Cool, but not an issue. If you write a tutorial, I'd merge into docs.
