### ISSUE TITLE
tinygrad is growing! should be tiny! add CI test for < 1000 lines

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#21]
I deleted all the fastconv crap because it wasn't tiny. Output from sloccount:

```
SLOC    Directory       SLOC-by-Language (Sorted)
325     tinygrad        python=325
260     test            python=260


Totals grouped by language (dominant language first):
python:         585 (100.00%)
```

Can someone add sloccount to CI and have it fail if it ever gets above 1000?

Also, no code golf, but refactors that reduce complexity are very welcome.

**Comment by Liamdoult** [comment]
@geohot Why don't you just make tinygrad-lib and put all the logic in there? Then tinygrad will always be less than 5 lines? 🤣
