### ISSUE TITLE
Dev Tools

### ISSUE THREAD

**Issue by iainwo** [geohot/tinygrad#214]
Hi all,

What do you think about adding some dev tools to the repo?

- [ ] requirements.txt
- [ ] makefile
  - [ ] `test` target - to run pytest (and linter too)
  - [ ] `create_environment` target - to install development dependencies into virtual env / conda
  - [ ] `build` target - to create the python package
  - [ ]  could call the makefile wrapper from ci

Here is style of Makefile I was thinking about: https://github.com/drivendata/cookiecutter-data-science/blob/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D/Makefile

Are these ideas too heavy weight?

**Comment by Liamdoult** [comment]
I think setuptools can do all of this. I don't think a makefile is necessary. But cleaning the `setup.py` to do all of the above would probably be useful.

**Comment by geohot** [comment]
I support adding to setuptools, submit a PR if you'd like.
