### ISSUE TITLE
 TestTinygradGPU.test_backward_pass_diamond_model not repeatable

### ISSUE THREAD

**Issue by EvanSchalton** [geohot/tinygrad#215]
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=1e-05
E       
E       Mismatched elements: 1 / 9 (11.1%)
E       Max absolute difference: 2.670288e-05
E       Max relative difference: 2.6658067e-06
E        x: array([[ 3.533231e+01,  0.000000e+00,  0.000000e+00],
E              [-1.361086e-02,  1.760480e-03,  4.752686e-01],
E              [-1.137313e-01, -1.956403e-02,  0.000000e+00]], dtype=float32)
E        y: array([[ 3.533228e+01, -0.000000e+00,  0.000000e+00],
E              [-1.361088e-02,  1.760482e-03,  4.752685e-01],
E              [-1.137312e-01, -1.956408e-02,  0.000000e+00]], dtype=float32)

Running the tensor test suite over and over again results in periodic failures ~1:10, tolerance is too high

**Comment by geohot** [comment]
Would merge PR to fix.
