### ISSUE TITLE
Division by zero in logsoftmax

### ISSUE THREAD

**Issue by marcelbischoff** [geohot/tinygrad#219]
I was running `examples/transformer.py` and I am getting
`ops_cpu.py:168: RuntimeWarning: divide by zero encountered in log
  return np.log(softmax)`

**Comment by kartik4949** [comment]
we can use with ignore context manager or add a small alpha value

**Comment by geohot** [comment]
I shouldn't be using logsoftmax there. Have to fix it to use softmax

**Comment by marcelbischoff** [comment]
For me, transformer still collapses, loss becomes nan and accuracy .17ish

**Comment by geohot** [comment]
Yea, me too. Not sure why, it wasn't the interior logsoftmax. Maybe it needs the LayerNorm I didn't write? Or the dropout.

**Comment by kartik4949** [comment]
i dont think dropout or layernorm caused the nans.

**Comment by marcelbischoff** [comment]
@geohot how would you do transpose, just copying all the tensor seems to be stupid. It would have been good if we would not only save the shape but also the strides. But maybe that is too much complexity.

**Comment by geohot** [comment]
Oh I'd just copy it.

**Comment by marcelbischoff** [comment]
Yeah, strides are a bad idea probably. Can do the naive transpose or here is something a bit faster: https://github.com/sschaetz/nvidia-opencl-examples/blob/master/OpenCL/src/oclTranspose/transpose.cl

**Comment by geohot** [comment]
Whatever works.

**Comment by marcelbischoff** [comment]
#221 seems to work

**Comment by geohot** [comment]
I think adding the subtraction of the max in softmax is the last instability fix. Can merge once we have max op for GPU.

**Comment by geohot** [comment]
Fixed
