### ISSUE TITLE
Make MaxPool2D a second class op

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#224]
I think it's doable with a Reshape and a Max. Though we'd also need to add slice as a first class op to handle the boundaries.

**Comment by kartik4949** [comment]
Look my pr on slice works on gpu and cpu 
But i closed it long back due to refactor issue :)

**Comment by geohot** [comment]
I'm thinking Slice and Pad2D can be the same first class op, which allows any axis to be expanded or shrank.

**Comment by geohot** [comment]
Would look like:
Slice (to make multiple of kernel size)
Reshape (to break out the kernel axes)
Max (to run the max pool, needs to support multiaxis)

**Comment by kartik4949** [comment]
Slice 
X[1:3,2,3:4] worked fine on gpu and cpu.

**Comment by geohot** [comment]
Which PR?

**Comment by kartik4949** [comment]
#183

**Comment by geohot** [comment]
To start, it's in the wrong place. It shouldn't be in tensor.py, it should be in the accelerators and implemented like an op. Then the slice python magic should be a second class op.

**Comment by kartik4949** [comment]
hmm.. you are right may be I can reopen, and start fresh with op like implementation

**Comment by geohot** [comment]
Okay, merged with an Unpad2D. That's generic on both the CPU and GPU, but it can't really be a second class op. And the GPU still needs max.

**Comment by kartik4949** [comment]
GPU max I will work now :)

**Comment by marcelbischoff** [comment]
Max you can do with reduce op but not sure how to do the backward because you need argmax, not?

**Comment by geohot** [comment]
Yea, you need argmax too.

**Comment by marcelbischoff** [comment]
Axis should just work with the reduce_op for the forward pass (the current or #203). I am wondering if the backward pass could be just comparing the input and output of max (using broadcasting in `binary_op`) to do backward.

**Comment by marcelbischoff** [comment]
Without axis it works. Just pushing it to #203. Axis could also magically work but reduce_op cannot have single argument axis.

**Comment by geohot** [comment]
Done

**Comment by hemangjoshi37a** [comment]
I agree with the solution proposed by `geohot` for making `MaxPool2D` a second class op using `Slice`, `Reshape`, and `Max`. I also understand the issue around `Slice` being a second class op, and the refactor issue mentioned by `kartik4949`.

To simplify things and ensure we are writing highly optimized and maintainable code, I suggest we could create a class `SecondClassOp` and implement our second class operations like `Slice`, `Reshape`, and `Max` within this class. This way, we can handle boundaries using the first class `Slice` operation.

```python
class SecondClassOp:
    def __init__(self, kernel_size):
        self.kernel_size = kernel_size

    def Slice(self, X):
        # Implement Slice here
        pass

    def Reshape(self, X):
        # Implement Reshape here
        pass

    def Max(self, X):
        # Implement Max here
        pass

    def MaxPool2D(self, X):
        X_sliced = self.Slice(X)
        X_reshaped = self.Reshape(X_sliced)
        return self.Max(X_reshaped)
```

This should ideally ensure that our code remains DRY (Don't Repeat Yourself) and we can implement each operation with GPU and CPU compatibility in mind. As for the argmax issue for the backward pass mentioned by `marcelbischoff`, I think comparing the input and output of max (using broadcasting in binary_op) for backward could indeed be the way to go. I can draft a more detailed implementation if this approach seems worthwhile.
