### ISSUE TITLE
Replace Pad2D and Unpad2D with Slice

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#225]
Slice takes two args for each axis. If the args are good for Numpy, they work like Numpy, but they can also pad with 0s by being larger than the axis.

pad2d will remain as a second class op, and unpad2d will just be replaced by Slice.

**Comment by kartik4949** [comment]
if im not wrong u mean
```
tensor  = Tensor(np.random.rand[10,10])
tensor.slice(0:12, 0:12, padding=0)
```
will pad two 0s on two sides?

**Comment by geohot** [comment]
Wrote Slice for CPU, tests are broken until it's written for GPU
