### ISSUE TITLE
Any interest in adding a DataLoader?

### ISSUE THREAD

**Issue by teddykoker** [geohot/tinygrad#239]
I have implemented a multi-process dataloader (similar to `torch.utils.data.DataLoader`) at [teddykoker/tinyloader](https://github.com/teddykoker/tinyloader/blob/cb62482ec2d23d51757d2f50c8159f124499662b/dataloader.py#L52-L135) in < 100 lines of code. Would be happy to submit a PR here if desired.

**Comment by skoshx** [comment]
Great work! The code is incredibly clean and readable! I think it would be a great addition to the `extras`. Defenitely will be adding this to our fork.

**Comment by Meehai** [comment]
Is rolling your own multi threaded queue better than using https://github.com/justheuristic/prefetch_generator/ or is the idea to have 0/minimal external dependencies?

**Comment by skoshx** [comment]
@Meehai @teddykoker 's implementation is clean and similar to the Torch DataLoader API, so I think it plays well with the goal of having a) a readable source and b) a torch-like API.

**Comment by geohot** [comment]
See comment on data loader PR. I'd devote max 100 lines to this. Ideally merging it reduces lines.
