### ISSUE TITLE
Tinygrad RAM usage climbing in forward pass of YOLO model. 30+GB RAM usage.

### ISSUE THREAD

**Issue by skoshx** [geohot/tinygrad#242]
So this is just something I have noticed when recreating YOLO model using tinygrad. The RAM usage goes up to 30+GB when running the forward pass through the numerous convolutional layers. This results in the Python process being killed after taking up too much ram.

So basically the model is being run in a loop of all the layers, and while the loop is running, and the input is being forwarded through the layers, the RAM usage just climbs higher and higher for every iteration, no memory is ever freed after an iteration.

Does anyone have any idea what could be causing this? It's as if conv2d, pad2d & add operations create new objects, and the old one isn't being garbage collected...

Edit: Ran the model on GPU, and noticed that this RAM issue only occurs running on CPU... Also with the amount of Convs, this runs really quick on GPU.

**Comment by marcelbischoff** [comment]
There have been problems like this before. Some have been fixed. Take a look at `https://github.com/geohot/tinygrad/blob/master/test/test_gc.py` how to check if the number of tensors explodes!

**Comment by skoshx** [comment]
@marcelbischoff Ok thank you, will look into it. For now, running on GPU is the quickest fix, but will fix this when I get the full yolo model working.

**Comment by marcelbischoff** [comment]
Ah, on the CPU I never had that issue.

**Comment by skoshx** [comment]
Okay, somehow this issue just completely disappeared after a while of running on GPU. Weird, but ok :D

**Comment by skoshx** [comment]
Turns out this issue surfaces again after running YOLO on CPU using "webcam". Have to look into this issue a bit.
