### ISSUE TITLE
Data structure of ANE instructions is in the ANE firmware

### ISSUE THREAD

**Issue by geekwish** [geohot/tinygrad#249]
Firmware Path: Firmware/ane/h11_ane_fw_quin.im4p

Related Function: CSneTMDrv::ParseTD(void const*,ulong,ANERegs_t *,ane_TD_HEADER_t *,bool)

I also wrote an ANEDisassembler, I hope it will be useful to you. 

https://github.com/antgroup-arclab/ANETools/tree/main/ANEDisassembler

**Comment by geohot** [comment]
Cool! I didn't find that in the firmware, I ended up with a similar disassembler by guessing.
