### ISSUE TITLE
How to write my own deep learning framework ?

### ISSUE THREAD

**Issue by PKUFlyingPig** [geohot/tinygrad#250]
I dream about writing my own DL framework, but the source code of pytorch is a little overwhelming. Although tiny grad is quite light-weight, it is still hard for me to understand how to start my own implementation. Could you please offer some idea about where should I start ? Or is there some great tutorial to follow ?

**Comment by 336655asd** [comment]
I have the same dream as you. I start with [micrograd](https://github.com/karpathy/micrograd) which is a simper framework. Then is [tinygrad](https://github.com/geohot/tinygrad), finally I will try a pytorch-like framework. 
During each framework, I think Tensor is the most fundamental class and you can start with it. Based on Tensor are different ops as well as  their forward and backward methods. Next step is from ops to layers and more complex things.
Looking forward to seeing your own framework soon.

**Comment by heytanay** [comment]
There's a very informative video playlist where Joel grus teaches how to code a PyTorch like Automatic differentiation framework using numpy.

[Here's the link](https://youtube.com/playlist?list=PLeDtc0GP5ICldMkRg-DkhpFX1rRBNHTCs)

It helped me in making a similar toy project.

**Comment by BrianWisniewski** [comment]
Maybe consider moving this to the discussions tab?

**Comment by nogira** [comment]
read the book "data science from scratch"
