### ISSUE TITLE
__getitem__ does not work for a single integer index

### ISSUE THREAD

**Issue by TZTsai** [geohot/tinygrad#251]
For example, let a = Tensor([1,2,3]), and if I try to get a[0], it will raise an error.

".../tensor.py", line 207, in __getitem__
     arg.append((s.start if s.start is not None else 0,
AttributeError: 'int' object has no attribute 'start'

**Comment by skoshx** [comment]
#254 Once this gets merged, this will work!

**Comment by skoshx** [comment]
@TZTsai I think you can close this one now, as it's fixed in the latest version.
