### ISSUE TITLE
ERROR: Package 'tinygrad' requires a different Python: 3.7.5 not in '>=3.8'

### ISSUE THREAD

**Issue by ArtificialZeng** [geohot/tinygrad#277]
Error while installation 
pip3 install git+https://github.com/geohot/tinygrad.git --upgrade

**Comment by ArtificialZeng** [comment]
my python version is 3.7.5

**Comment by sixChar** [comment]
According to the message your python version needs to be at least 3.8.something. you need to upgrade your python version.

**Comment by ArtificialZeng** [comment]
> According to the message your python version needs to be at least 3.8.something. you need to upgrade your python version.

Very Thks！ It‘s solved.
