### ISSUE TITLE
Failed to call ANE_PowerOn

### ISSUE THREAD

**Issue by peyer** [geohot/tinygrad#282]
I got return value of -536870195 while calling ANE_PowerOn, how could I fix it?

**Comment by geohot** [comment]
You have to disable SIP

**Comment by peyer** [comment]
Sadly. I have disable SIP and try to run testconv.py, it also return -536870195
![e2418f384414c46095b16cb60687291cb06142ac](https://user-images.githubusercontent.com/19945545/151684451-325bbc91-fcea-45f5-ab29-6599c2a8128d.png)
