### ISSUE TITLE
tinygrad + JIT compiler?

### ISSUE THREAD

**Issue by Runkli** [geohot/tinygrad#298]
[numba](https://github.com/numba/numba) accelerates numpy arrays. tinygrad uses numpy arrays.
https://github.com/geohot/tinygrad/pull/13 This pull request adds convs with numba, are there any plans on pushing forward this type of acceleration?

**Comment by geohot** [comment]
If you want speed, you shouldn't be using the CPU. The CPU is really just a reference implementation.
