### ISSUE TITLE
Reduce line count!

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#305]

**Comment by Henistein** [comment]
Does eliminating lines between statements also count?

**Comment by rylan-justice** [comment]
Hi, @geohot! Would you mind if I minified imports like this?
```python
import module, module, module as abbreviation
```
If I import them like this, it will reduce the line count significantly.

**Comment by Liamdoult** [comment]
@Henistein No, Sloccount is used to count lines: https://github.com/geohot/tinygrad/blob/050636bcb1068beff62ed23392de02e2f5d80f22/.github/workflows/test.yml

**Comment by geohot** [comment]
It's 961 lines now!

Done through the power of refactoring, not code golf.
