### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#326]
- [x] Replace broadcasting with MovementOps.EXPAND
- [ ] Add Div to mlops
- [x] Add conv support for padding and dilation
- [x] Consider if we can add something to combine transpose and weight grad to reduce processing ops
- [x] MovementOps.FLIP?

**Comment by orausch** [comment]
FYI, if you don't mind getting a bit spicier in terms of memory safety, you can replace all of your movement ops with a strided view op:
E.g.;
```
view = lambda x, shape, strides, offset: \
  np.ndarray(buffer=x.data, shape=shape, strides=strides, offset=offset, dtype=x.dtype)
x = np.arange(3).reshape(-1,1)
y = np.random.rand(3, 4)
```
* Expand/Broadcast: `view(x, (3, 4), (8, 0), 0) == np.broadcast_to(x, (3, 4))`
* Flip: `view(y, (3, 4), (-32, -8), 8 * 12 - 8) == np.flip(y)`
* Transpose: `view(y, (4, 3), (8, 32), 0) == np.transpose(y)`
* Reshape: `np.reshape(y, -1) == view(y, (12,), (8,), 0)`
* Slice: `view(y, (4,), (8,), 8 * 4) == y[1]`, `view(y, (3,), (32,), 8) == y[:, 1]`
* And many others

Notice that you don't actually need to launch a kernel to perform a view op like above; if your other kernels are stride aware you effectively "fuse" the data-movement into the preceding or following op.

Note that the stride tricks can run out when input arrays are no longer contiguous, and sometimes you will need to materialize the array with a copy.  However, with an efficient copy op ([hint](https://github.com/microsoft/onnxruntime/blob/1685ab81381fdc4d6948bcd19c5729c06a0cd49c/onnxruntime/core/providers/cpu/tensor/copy.cc#L235)), this is still cheaper or equal to the runtime cost of doing the data-movement eagerly like you're doing now.

NumPy does these tricks internally, and torch does some of them (the ones that don't involve negative strides; they don't support that yet).

**Comment by geohot** [comment]
So I actually want to do it all without copies. Movement ops should all always be free, then there's a kernel to make contiguous (or stride aware kernels).

See my start here: https://github.com/geohot/tinygrad/pull/328

I understand that say, a permute followed by a reshape might traditionally require a copy, but I'll solve this by using "virtual dimensions". A real dimension can contain multiple virtual dimensions, and the virtual dimensions are what is actually used.

**Comment by geohot** [comment]
ShapeTracker works!
