### ISSUE TITLE
EfficientNet doesn't work!

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#33]
It should be a cat. It is a washer.

Who can fix. I will be impressed.

**Comment by geohot** [comment]
Hmm, my groups in Conv2D is wrong

**Comment by geohot** [comment]
Working on it in #34

**Comment by geohot** [comment]
Now it's a "coho"

**Comment by marcelbischoff** [comment]
First of all, cat needs to be replaced by ![](https://github.com/karpathy/micrograd/blob/master/puppy.jpg)

**Comment by geohot** [comment]
It works! Will merge PR for micrograd dog.

**Comment by marcelbischoff** [comment]
258 6.85845 Samoyed, Samoyede
