### ISSUE TITLE
Error in Example : mnist_gan.py and yolov3.py

### ISSUE THREAD

**Issue by hemangjoshi37a** [geohot/tinygrad#371]
Code I ran : [./examples/mnist_gan.py ](https://github.com/geohot/tinygrad/blob/master/examples/mnist_gan.py)
and [./examples/yolov3.py](https://github.com/geohot/tinygrad/blob/master/examples/yolov3.py)
I have installed "Extra" module using pip.

Error : 
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_8351/3158765221.py in <module>
      8 
      9 from tinygrad.tensor import Tensor, Function, register
---> 10 from extra.utils import get_parameters
     11 import tinygrad.nn.optim as optim
     12 from test_mnist import X_train

ModuleNotFoundError: No module named 'extra.utils'
```

Please help me solve this issue @geohot

**Comment by Henistein** [comment]
Try to run like this: `python3 -m examples.mnist_gan`

**Comment by hemangjoshi37a** [comment]
> Try to run like this: `python3 -m examples.mnist_gan` from the root folder

Thank you for quick support.
