### ISSUE TITLE
Get back to 1000 lines

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#405]
tensor.py -- 245 lines
mlops.py -- 135 lines

These 380 are pretty good, maybe 10 to lose.

helpers.py -- 41 lines
ops.py -- 58 lines
lazy.py -- 177 lines (there's 20 lines to lose here)
shapetracker.py -- 119 lines (there's 20 lines to lose here, use AST for shapes)

Extras:

graph.py -- 59 lines (there's 10 to lose here)
nn/ -- 103 lines
llops/ -- 234 lines (there's ~30 lines to lose here, merge exec_ast and _processing_op)

Have to lose 174 lines. I think it's time nn moves out

**Comment by divamgupta** [comment]
1000 lines are cool, but what is not cool - it's having less than 1000 lines at the cost of not having docstrings and readable code.

**Comment by jla524** [comment]
> 1000 lines are cool, but what is not cool - it's having less than 1000 lines at the cost of not having docstrings and readable code.

I agree that the code can be more readable, but I believe the line counter ([sloccount](https://dwheeler.com/sloccount/)) doesn't count docstrings. (It's counting the physical Source Lines of Code, or SLOC.) So we can add docstrings without increasing the line count.

**Comment by karolherbst** [comment]
please just get rid of this rule, if your code looks like this instead: https://github.com/geohot/tinygrad/blob/master/tinygrad/llops/ops_gpu.py#L117-L123

It's a terrible idea, has no benefit and creates the wrong incentive.

**Comment by Lunarequest** [comment]
I completely agree. Its borderline impossible to follow, and its a recipe for a legacy unmaintainable code base that no one but the person who wrote it understands.

**Comment by arizvisa** [comment]
y'all are no fun.

**Comment by geohot** [comment]
> please just get rid of this rule if otherwise your code looks like this instead: https://github.com/geohot/tinygrad/blob/master/tinygrad/llops/ops_gpu.py#L117-L123
> 
> It's a terrible idea, has no benefit and creates the wrong incentive.

I agree that's terrible code. Will fix in newgpu branch

**Comment by catasaurus** [comment]
I think the under 1000 lines or under 2000 lines goal works if the goal is not to have shorter code by making tinygrad more compact, its to have shorter code by making tinygrad more simple.

**Comment by metacritical** [comment]
1000 Lines is a great target simple is better and maintainable.
