### ISSUE TITLE
Using vecLib.framework instead of M1 AMX machine code?

### ISSUE THREAD

**Issue by calledit** [geohot/tinygrad#429]
So I have been thinking about the M1 AMX work in the chonker branch...

If we look at pytorch, It uses the apple [accelerate framework(Accelerate.framework)](https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX11.3.sdk/System/Library/Frameworks/Accelerate.framework/Versions/A/Headers/Accelerate.h). 
The Accelerate.framework relies on  [vecLib.framework](https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX11.3.sdk/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers/vecLib.h).
In the vecLib.framework we have [cblas.h](https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX11.3.sdk/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers/cblas.h) which has the ops tinygrad deals with. Presumably it deals with all annoying details like caches sizes and things like that.

There is of course some performance penalties to calling a function and having it do stuff compared to writing machine code. But to me it seams like the performance penalty might be worth it if the reduction in complexity is large enough.

Maybe using cblas makes fusing certain operations hard?

**Comment by geohot** [comment]
The main issue with using a BLAS library is operations after the SUM, say like a RELU. The BLAS library would have to write the matrix out to RAM, the RELU kernel would have to read it, then it would write it back.

While we could make things faster today with a BLAS library, this gives up one of the long term gains possible with tinygrad. The RELU fusing already works today, and real gains will happen when we start fusing in the norm.
