### ISSUE TITLE
Many GPU ops are missing for backward pass

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#43]
Please write

**Comment by shanecandoit** [comment]
Your chance to learn some openCL GPU programming!

This file (https://github.com/geohot/tinygrad/blob/master/tinygrad/opsgpu.py) only has these GPU ops:

- Add
- Mul
- Sum
- Dot

This file (https://github.com/geohot/tinygrad/blob/master/tinygrad/ops.py) has these additional CPU ops.
These operations need to be implemented in [OpenCL wiki](https://en.wikipedia.org/wiki/OpenCL), [pyopencl docs](https://documen.tician.de/pyopencl/) and added to the "opsgpu.py" file.

- [ ] Sub
- [ ] Pow
- [ ] Dot
- [ ] Pad2D
- [ ] Reshape
- [ ] ReLU
- [ ] Sigmoid
- [ ] LogSoftmax
- [ ] Conv2D
- [ ] MaxPool2D
- [ ] AvgPool2D

**Comment by geohot** [comment]
All forward passes should be good, just backward passes broken.
