### ISSUE TITLE
Neg operator

### ISSUE THREAD

**Issue by calledit** [geohot/tinygrad#437]
The neg operator is converted to a sub at tinygrad/tensor.py:263
Now, that neg is a hardware supported llop. It seams strange to convert every use of neg to sub on the higher abstraction layer.

What is the intent?

**Comment by geohot** [comment]
The constant folder should deal with this, then it's one less op. But I'm fine with adding it, it might make optimization easier, will merge PR.

**Comment by geohot** [comment]
Constant folder is fine
