### ISSUE TITLE
python3 examples/yolov3.py: assert self.lazydata.realized is None AssertionError

### ISSUE THREAD

**Issue by dh-bccw** [geohot/tinygrad#442]
python3 examples/yolov3.py:

...
Modules length: 24
Loading weights file (237MB). This might take a while…
running inference…
Traceback (most recent call last):
  File "/home/dh/tinygrad/examples/yolov3.py", line 628, in <module>
    prediction = infer(model, img)
  File "/home/dh/tinygrad/examples/yolov3.py", line 244, in infer
    prediction = model.forward(Tensor(img.astype(np.float32)))
  File "/home/dh/tinygrad/examples/yolov3.py", line 561, in forward
    x = predict_transform(x, inp_dim, anchors, num_classes)
  File "/home/dh/tinygrad/examples/yolov3.py", line 321, in predict_transform
    prediction.gpu_()
  File "/home/dh/tinygrad/tinygrad/tensor.py", line 74, in to_
    assert self.lazydata.realized is None
AssertionError

What is the problem? thank you!

**Comment by calledit** [comment]
There has been large changes in tinygrad since that example was written and tinygrads API has changed.

You can run the example on an older version of tinygrad
```
git checkout 121d5a17ee436d043bcd49053ef4dc4114a56718
GPU=1 python3 examples/yolov3.py
```

You could send in a pull request.. but since the API is so unstable it might be a bit wasteful. Stuff will likely change again. Or so I think. For example, operation fusing which is in the pipeline will require at least one change to the tinygrad API.

**Comment by dh-bccw** [comment]
> There has been large changes in tinygrad since that example was written and tinygrads API has changed.
> 
> You can run the example on an older version of tinygrad
> 
> ```
> git checkout 121d5a17ee436d043bcd49053ef4dc4114a56718
> GPU=1 python3 examples/yolov3.py
> ```
> 
> You could send in a pull request to fix it.. but since the API is so unstable it might be a bit wasteful. Stuff will likely change again. Or so I think. For example, operation fusing which is in the pipeline will require at least one change that I can think of to the tinygrad API.

Thank you very much for your help. I'll see if I can solve this problem.
