### ISSUE TITLE
Suggestion to add type hints to TinyGrad

### ISSUE THREAD

**Issue by 0xArty** [geohot/tinygrad#448]
I want to suggest adding type hints to the TinyGrad library to improve code readability and maintainability.

For example, consider the following without type hints:

```python
class Tensor:
  training, no_grad = False, False

  def __init__(self, data, device=Device.DEFAULT, requires_grad=None):
```

Without type hints, it is not clear what types of values data should be. This can lead to confusion and potential bugs if the class is created with values of the wrong type.

On the other hand, if we add type hints to the function, it becomes much clearer when type hints are added:

```python
class Tensor:
  training: bool = False
  no_grad: bool = False

  def __init__(self, data: Union[list, np.ndarray, LazyBuffer], device: Device=Device.DEFAULT, requires_grad: Optional[bool]=None):
  ```

Overall, I believe that adding type hints to TinyGrad would significantly improve the readability and maintainability of the library, and would greatly benefit anyone working with it.

If you think it would be useful, I'm happy to start adding them to the library.

Love what you're doing here. Thanks for reading!

**Comment by geohot** [comment]
There's some typing already, but if it's tastefully added I'll merge
