### ISSUE TITLE
Backward Error Running on Windows Anaconda Enviroment

### ISSUE THREAD

**Issue by BiophysNinja** [geohot/tinygrad#45]
torch forward pass:  20.993 ms
torch backward pass: 210.071 ms
------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                      Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------
                              aten::addmm_        19.93%      51.973ms        19.93%      51.973ms      30.217us          1720
                  aten::threshold_backward        11.94%      31.134ms        12.04%      31.387ms       3.139ms            10
                           aten::threshold        11.57%      30.184ms        11.65%      30.384ms       3.038ms            10
                aten::thnn_conv2d_backward         9.75%      25.432ms        40.07%     104.499ms      10.450ms            10
                               aten::fill_         9.45%      24.652ms         9.45%      24.652ms      50.310us           490
             aten::max_pool2d_with_indices         8.99%      23.435ms         9.10%      23.720ms       2.372ms            10
                              aten::select         7.79%      20.309ms         9.17%      23.919ms       6.165us          3880
                 aten::thnn_conv2d_forward         5.39%      14.059ms        14.23%      37.100ms       3.710ms            10
    aten::max_pool2d_with_indices_backward         2.61%       6.814ms         6.66%      17.368ms       1.737ms            10
                                  aten::mm         2.47%       6.444ms         2.51%       6.540ms     435.980us            15
------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 260.772ms

E
======================================================================
ERROR: test_mnist (__main__.TestConvSpeed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Nehad Hirmiz\Documents\Programming\Python\Tutorials\tinygrad\test_speedynet.py", line 83, in test_mnist
    out.backward()
  File "c:\ProgramData\Anaconda3\envs\deeptorch\lib\site-packages\tinygrad\tensor.py", line 68, in backward
    t.backward(False)
  File "c:\ProgramData\Anaconda3\envs\deeptorch\lib\site-packages\tinygrad\tensor.py", line 68, in backward
    t.backward(False)
  File "c:\ProgramData\Anaconda3\envs\deeptorch\lib\site-packages\tinygrad\tensor.py", line 68, in backward
    t.backward(False)
  [Previous line repeated 1 more time]
  File "c:\ProgramData\Anaconda3\envs\deeptorch\lib\site-packages\tinygrad\tensor.py", line 63, in backward
    if g.shape != t.data.shape:
AttributeError: 'tuple' object has no attribute 'shape'

**Comment by BiophysNinja** [comment]
I get this error when I run any training all well. 
The loss Tensor is seen as a tuple even though in debug mode is clearly stated as a Tensor
I can fix it by adding the line:
loss =Tensor(loss)
not sure what is happening

**Comment by geohot** [comment]
Can’t repro here, but if you figure it out, I’ll merge the PR

**Comment by BiophysNinja** [comment]
I am not sure why this is happening but checking both t and g are instances of Tensor seems to fix it (line 61 in tensor.py)
```
      if g is None or isinstance(g,Tensor) or isinstance(t,Tensor):
        continue
```

**Comment by pedrogengo** [comment]
Can you do `pip freeze`? Because I run `python -m pytest` and I've passed in all tests here.

**Comment by BiophysNinja** [comment]
> Can you do `pip freeze`? Because I run `python -m pytest` and I've passed in all tests here.

Here is what I get 
tinygrad==0.2.2
toml==0.10.2
torch==1.7.0
torchaudio==0.7.0
torchvision==0.8.1
tqdm==4.51.0
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1602702424206/work
urllib3==1.25.11
wincertstore==0.2

please let me know if you see anything unusual. 
Many thanks for taking the time to help

**Comment by pedrogengo** [comment]
Did you install using `pip install tinygrad` or you clone the repo and use `pip install -r requirements.txt`?

**Comment by pedrogengo** [comment]
I created a new conda env (python==3.8) and ran the following commands, after activating the env:
`pip install tinygrad`
`git clone https://github.com/geohot/tinygrad`
`cd tinygrad`
`pip install -r requirements.txt`
`python -m pytest`

And when I list my env packages I get:

atomicwrites==1.4.0
attrs==20.2.0
certifi==2020.6.20
chardet==3.0.4
colorama==0.4.4
future==0.18.2
gast==0.3.3
google-auth==1.20.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
h5py==2.10.0
idna==2.10
iniconfig==1.1.1
Keras-Preprocessing==1.1.2
Markdown==3.2.2
numpy==1.19.4
oauthlib==3.1.0
opt-einsum==3.3.0
packaging==20.4
Pillow==8.0.1
pluggy==0.13.1
py==1.9.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
pytest==6.1.2
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scipy==1.4.1
six==1.15.0
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorflow==2.3.0
tensorflow-estimator==2.3.0
tinygrad==0.2.2
toml==0.10.2
torch==1.6.0+cpu
torchvision==0.7.0+cpu
tqdm==4.51.0
urllib3==1.25.11
Werkzeug==1.0.1
wincertstore==0.2
wrapt==1.12.1


Try to do that

**Comment by BiophysNinja** [comment]
Hi Pedro, 
Thanks a million. That actually worked. It still having problem with test_mnist.py
(tiny) C:\Users\Nehad Hirmiz\Documents\Programming\Python\Tutorials\tinygrad\tinygrad-master>
(tiny) C:\Users\Nehad Hirmiz\Documents\Programming\Python\Tutorials\tinygrad\tinygrad-master>
(tiny) C:\Users\Nehad Hirmiz\Documents\Programming\Python\Tutorials\tinygrad\tinygrad-master>cd test

(tiny) C:\Users\Nehad Hirmiz\Documents\Programming\Python\Tutorials\tinygrad\tinygrad-master\test>python test_mnist.py
Traceback (most recent call last):
  File "test_mnist.py", line 5, in <module>
    from tinygrad.tensor import Tensor, GPU
ImportError: cannot import name 'GPU' from 'tinygrad.tensor' (C:\ProgramData\Anaconda3\envs\tiny\lib\site-packages\tinygrad\tensor.py)

(tiny) C:\Users\Nehad Hirmiz\Documents\Programming\Python\Tutorials\tinygrad\tinygrad-master\test>cd ..

(tiny) C:\Users\Nehad Hirmiz\Documents\Programming\Python\Tutorials\tinygrad\tinygrad-master>python -m pytest
============================================================================================== test session starts ===============================================================================================
platform win32 -- Python 3.8.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: C:\Users\Nehad Hirmiz\Documents\Programming\Python\Tutorials\tinygrad\tinygrad-master
collected 25 items

test\test_mnist.py ...s                                                                                                                                                                                     [ 16%]
test\test_net_speed.py .                                                                                                                                                                                    [ 20%]
test\test_nn.py .                                                                                                                                                                                           [ 24%]
test\test_ops.py .............                                                                                                                                                                              [ 76%]
test\test_optim.py ...                                                                                                                                                                                      [ 88%]
test\test_tensor.py ...

**Comment by pedrogengo** [comment]
Can you show me your directory structure? Why do you have _tinygrad_master_ folder?

**Comment by pedrogengo** [comment]
I know why you are getting this error. This is because the pypi library is different from the git library.

So, you should make:

`pip uninstall tinygrad`

Go to the mother path (before the tinygrad path) and run the command:

`pip install -e .\tinygrad`

**Comment by pedrogengo** [comment]
After that, your git local repo will be the reference for the tinygrad. So, when you make get the newest version from the repo, your library will update too.

**Comment by BiophysNinja** [comment]
> After that, your git local repo will be the reference for the tinygrad. So, when you make get the newest version from the repo, your library will update too.

That did it :) Thank you very much for the kind help. Have a great day

- Nehad
