### ISSUE TITLE
Example code doesn't show actual tensor

### ISSUE THREAD

**Issue by faisalmemon** [geohot/tinygrad#453]
When you run the README.md example for tiny grad:

```python
from tinygrad.tensor import Tensor

x = Tensor.eye(3, requires_grad=True)
y = Tensor([[2.0,0,-2.0]], requires_grad=True)
z = y.matmul(x).sum()
z.backward()

print(x.grad)  # dz/dx
print(y.grad)  # dz/dy
```

It prints out
```
<Tensor <LB (3, 3) op:MovementOps.RESHAPE> with grad None>
<Tensor <LB (1, 3) op:MovementOps.RESHAPE> with grad None>
```

but it should be printed out via numpy.  e.g. use `x.grad.numpy()` and `y.grad.numpy()` to get output
```
[[ 2.  2.  2.]
 [ 0.  0.  0.]
 [-2. -2. -2.]]
[[1. 1. 1.]]
```

**Comment by JJJJJJJJJJJJJJJl** [comment]
That's on purpose! If you really want that behavior simply comment the [repr](https://github.com/geohot/tinygrad/blob/master/tinygrad/tensor.py#L39-L40) function in the Tensor class out ^^

**Comment by JJJJJJJJJJJJJJJl** [comment]
That's on purpose! If you really want that behavior simply change the [repr](https://github.com/geohot/tinygrad/blob/master/tinygrad/tensor.py#L39-L40) to: `def __repr__(self):
    return str(self.numpy())` for example.

**Comment by faisalmemon** [comment]
Can you suggest an alternative code change to README to make it clear that the example requires you to define how the Tensor is realised to be equivalent output to Torch.  I think I may have totally missed the point of the example in the README.

**Comment by JJJJJJJJJJJJJJJl** [comment]
Sure they output different things, but as you said that's not really the point. The point is to show how similar tinygrad code is compared to pytorch, thus no need to learn a whole different syntax to write some ml stuff ^^
