### ISSUE TITLE
Code style formatting ?

### ISSUE THREAD

**Issue by pythops** [geohot/tinygrad#473]
Can we agree on a code style (and tools).
what about:
- [ruff](https://github.com/charliermarsh/ruff) for linting and imports formatting (replacing [isort](https://github.com/PyCQA/isort)
- [black](https://github.com/psf/black) for code formatting

the configuration file `pyproject.yaml` could look like this 

```
[tool.black]
line_length = 100
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
  | __pycache__
  | build
  | dist
)/
'''

[tool.mypy]
check_untyped_defs = true
namespace_packages = true
pretty = true
show_error_context = true

[tool.ruff]
line-length = 100
fix = true

exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
  ".venv",
]

target-version = "py310"
```

**Comment by geohot** [comment]
Why?

If tools improve correctness, I'm interested. But just style formatters are bleh for large companies so all workers are interchangeable drones, and make code less readable to me.

**Comment by pythops** [comment]
> Why ?

for those reasons:
- improve code readability
- catch some errors like unused imports or variables
- enforce editors configuration: some devs have their editors configured to format the code on saving automatically using those tools, without any configuration from local repo, the editors format based on default conf.

I don't think it's something that large companies uses only. Many active open source projects use that to make contributing easy for everyone.

**Comment by geohot** [comment]
Again, "catch errors" is fine, and anything you'd like to add to that end I'm open to. For readability and editors is not.
