### ISSUE TITLE
LLVM/GPU CI Tests are slow

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#527]
Both the LLVM and OpenCL tests are slow. I'm surprised the pip cache didn't help more with the "Install Dependencies" step.

GPU Tests are taking 7m 41s (and are currently run with OPT=1!)
LLVM Tests are taking 6m 58s

In contrast, CPU and Torch tests are taking ~2 minutes.

Anyone want to look into this? Speeding up "Install Dependencies" would be welcome also

**Comment by jla524** [comment]
The [GitHub-hosted runners don't have a GPU](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), so CL uses the CPU for GPU tests. I ran a [modified test](https://github.com/jla524/tinygrad/actions/runs/4090705359/jobs/7054302509) to confirm this.
```
>Run python -c "import pyopencl as cl; print(sum([x.get_devices(device_type=cl.device_type.GPU) for x in cl.get_platforms()], []))"
[]

>Run DEBUG=1 OPT=1 GPU=1 python -m pytest -s -v
...
using [<pyopencl.Device 'Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz' on 'Intel(R) OpenCL' at 0x56047f8bd3d8>]
```

For reference, a Google Colab instance takes 10m 12s on a GPU (NVIDIA Tesla T4) and 35m 16s on a CPU (Intel Xeon).

Do you want to try using a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) with a powerful GPU?

**Comment by geohot** [comment]
Nah, self hosted runners add a ton of complexity. GPU emulation is fine, let's just profile where it's slow and improve it.

**Comment by jla524** [comment]
Sounds good. Here are the slowest tests on GPU:
```
97.35s call     test/test_train.py::TestTrain::test_efficientnet
44.74s call     test/test_ops.py::TestOps::test_conv2d
40.05s call     test/test_train.py::TestTrain::test_resnet
32.05s call     test/test_mnist.py::TestMNIST::test_conv
30.07s call     test/test_onnx.py::TestOnnxModel::test_benchmark_openpilot_model
27.15s call     test/test_mnist.py::TestMNIST::test_sgd
22.70s call     test/test_mnist.py::TestMNIST::test_rmsprop
19.21s call     test/test_train.py::TestTrain::test_transformer
18.62s call     test/test_train.py::TestTrain::test_vit
15.79s call     test/test_efficientnet.py::TestEfficientNet::test_car
15.39s call     test/test_efficientnet.py::TestEfficientNet::test_chicken_bigbatch
12.04s call     test/test_onnx.py::TestOnnxModel::test_efficientnet
10.43s call     test/test_ops.py::TestOps::test_padded_conv2d
5.37s call     test/test_ops.py::TestOps::test_padded_conv2d_bs1
3.76s call     test/test_ops.py::TestOps::test_asymmetric_padding_conv2d
3.42s call     test/test_efficientnet.py::TestViT::test_car
3.37s call     test/test_ops.py::TestOps::test_broadcast_partial
2.98s call     test/test_ops.py::TestOps::test_broadcast_full
2.94s call     test/test_speed_v_torch.py::TestSpeed::test_permute
2.78s call     test/test_mnist.py::TestMNIST::test_adam_onestep
2.55s call     test/test_speed_v_torch.py::TestSpeed::test_add
2.50s call     test/test_ops.py::TestOps::test_maxpool2d
2.49s call     test/test_mnist.py::TestMNIST::test_conv_onestep
2.42s call     test/test_speed_v_torch.py::TestSpeed::test_add_sq
2.41s call     test/test_onnx.py::TestOnnxModel::test_openpilot_model
2.37s setup    test/test_efficientnet.py::TestEfficientNet::test_car
2.10s call     test/test_ops.py::TestOps::test_strided_conv2d
2.09s call     test/test_optim.py::TestOptim::test_adam
2.02s call     test/test_ops.py::TestOps::test_dilated_conv2d
2.00s call     test/test_ops.py::TestOps::test_avgpool2d
```

**Comment by geohot** [comment]
I disabled the LLVM optimizer, that should bring down compile times a lot.

Within test_efficientnet, is most of those 97s spent actually running kernels?

**Comment by jla524** [comment]
Most of the time is spent on `optim.step()`, and it looks like [Adam is much slower than SGD](https://discuss.pytorch.org/t/optimizer-step-the-slowest/90820).

With Adam:
```
test/test_train.py::TestTrain::test_efficientnet stepping <class 'models.efficientnet.EfficientNet'> with 5.3M params bs 2
sampling took 0.000646
forward took 0.471470
zero_grad took 0.000083
backward took 0.456432
step took 79.415912
logging took 0.300535
done in 80188.98 ms
...
80.26s call     test/test_train.py::TestTrain::test_efficientnet
```

With SGD:
```
test/test_train.py::TestTrain::test_efficientnet stepping <class 'models.efficientnet.EfficientNet'> with 5.3M params bs 2
sampling took 0.000464
forward took 0.482933
zero_grad took 0.000079
backward took 0.455837
step took 50.076696
logging took 0.293684
done in 50854.10 ms
...
50.91s call     test/test_train.py::TestTrain::test_efficientnet
```

**Comment by geohot** [comment]
Seems like onnx2torch requires a lot of deps. I wonder what the lightest weight onnx runtime is and if we can switch to it?

**Comment by geohot** [comment]
The dep cache might on the whole be making things slower. Maybe the right idea is to cache a whole virtualenv?

**Comment by geohot** [comment]
Going to close this. Deps install time is down to like 35s, and GPU/LLVM are similarly slow for having to build the kernels

**Comment by jamesroberts** [comment]
#535 This should also help bring CI times down
