### ISSUE TITLE
Can't import fetch from ultis

### ISSUE THREAD

**Issue by cuong21951** [geohot/tinygrad#55]
ImportError: cannot import name 'fetch' from 'tinygrad.utils' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tinygrad/utils.py)
This occur when i'm running the example.
I'm not a py developer then

**Comment by mpizzzle** [comment]
It seems like the package is broken upstream when you install through pip3, if you install tinygrad using setup.py then this issue gets resolved.

**Comment by RakibFiha** [comment]
@cuong21951 if you cat `/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tinygrad/utils.py`, you will probably see that there is no function called `fetch` and hence it's happening, I reckon. 

> It seems like the package is broken upstream when you install through pip3, if you install tinygrad using setup.py then this issue gets resolved.

Solves the problem.
