### ISSUE TITLE
optim tests are only testing one step!

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#551]
Pretty useless for RMSProp and ADAM.

And should test SGD + momentum

**Comment by PatStiles** [comment]
Interested!

**Comment by EduardoPach** [comment]
Just created a pull request to fix this on #575

**Comment by elginbeloy** [comment]
Hey @geohot this is stale IIUC. You removed RMSProp [here](https://github.com/geohot/tinygrad/commit/30b795874abbbfd767e9d94bb7746641ffe0d57a) and added multistep ADAM already [here](https://github.com/geohot/tinygrad/blob/master/test/test_optim.py#L62C18-L66)
