### ISSUE TITLE
C backend (C code generation from model)

### ISSUE THREAD

**Issue by benmkw** [geohot/tinygrad#568]
Is a backend which generates c code possible/ in scope? 
(this is not really limited to c code, could be js/ rust whatever with very simple changes, just picking c as the most common use case)

Motivation: Maximum portability/ simplicity
_Recently I has much success with this approach for random forest models, much like https://github.com/nok/sklearn-porter but simpler/ handmade and I'd like to also use this for neural networks, if possible._

The whole thing would be similar to NN512, I also explored this a bit with `onnx -> c` but did not get very far yet due to the lack of time/ too much complexity https://github.com/onnx/onnx-mlir/issues/1668

My guess/ main question is that lazy evaluation would not work with c code generation because all the code would need to be generated + compiled at once so if tinygrad would fully switch to lazy ops this might not work?

**Comment by geohot** [comment]
Funny you mention this, I was just thinking about it. This for a company or a hobby project?

**Comment by benmkw** [comment]
> it would "compile" in the same way the openpilot model does.

good to know its generally in scope

> This for a company or a hobby project? Come discuss on the discord.

Its sadly not for a company, even the people at onnx-mlir where I joined a discussion to present the idea where hard to convince that this is actually useful.

_Onnx-mlir is also a very good idea generally, their api is just not very easy to use and its hard to distribute in an existing toolchain/ cross platform._

I think for large models a c backend likely is indeed not useful/ to slow but especially for smaller ones this should greatly expand the areas where one can deploy them.

**Comment by geohot** [comment]
Done, see tinygrad.org

**Comment by benmkw** [comment]
great work! thanks

its also amazing that it already works on wasm, really good showcase 👍 

just as a note/ braindump, the next possible steps from my POV are:
- making it more widely usable (onnx -> c instead of efficientnet)
- separating it from gpu code
  - adding more flavors to make it faster:
    - separate SIMD codepaths for wasm, x86, arm, (like NN512)
    - use BLAS for matmul instead of raw for loops
    - better tiling/ TODO profile/ probably memory bound
    - add restrict qualifiers to params if applicable

**Comment by geohot** [comment]
Never using BLAS, it should be able to generate code that maxes out the CPU. tinygrad doesn't link to libraries.

Improving the compiler to go from onnx / refactoring it to share more code with the openpilot compiler is great.

Restrict params are valid for GPU also, probably a 5 line PR I would merge.

Better tiling should be found with the KOPT.

**Comment by rTreutlein** [comment]
I am interested in ultra portable solutions like this and did a speed comparison (with a simple conv net) to dlib which was about 4x faster.  So i was wondering if there are any plans to work on the speed of the c backend.

**Comment by geohot** [comment]
If there's funding to make it faster, we can. 0 effort has been put into optimization.
