### ISSUE TITLE
apple m1 ventura onnx import error

### ISSUE THREAD

**Issue by sohaiberrabii** [geohot/tinygrad#587]
protobuf should be removed from direct dependencies for `pip install -e .'[testing]'` to work painlessly on m1 ventura.

`pip install onnx~=1.12.0` => builds from source and requires protobuf compiler
```
brew install protobuf
pip install protobuf~=3.19.0 onnx~=1.12.0
```
=> import onnx fails, (maybe because it is built against a different protobuf version from brew)

solutions: 

1. keep onnx 1.12.0
```
brew install protobuf
pip install onnx~=1.12.0
```
=> works but installs protobuf 3.20.1
=> remove direct dependency on protobuf from setup.py / update the dependency to protobuf 3.20

2. update onnx to 1.13.0, but it depends on protobuf<4,>=3.20.2
=> doesnt build from source, universal2 wheel available

**Comment by geohot** [comment]
I think upgrading onnx should be fine, want to submit a PR?

**Comment by geohot** [comment]
Thanks, merged!
