### ISSUE TITLE
Fuse RESHAPEs into PERMUTEs sometimes

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#591]
![Screenshot 2023-02-23 at 2 49 49 PM](https://user-images.githubusercontent.com/72895/221048569-d356d599-e676-4f96-921a-fecc3f318f3a.png)

**Comment by ImanHosseini** [comment]
Can you share an example? (of a fusable case like the shown graph)

**Comment by ImanHosseini** [comment]
Can we close this now? 
It seems that now in the case above (test_gemm) they are correctly fused since this PR:
https://github.com/geohot/tinygrad/pull/663/commits
