### ISSUE TITLE
ANE clock speed

### ISSUE THREAD

**Issue by philipturner** [geohot/tinygrad#596]
[335 MHz with 1024 FFMA pipelines](https://github.com/geohot/tinygrad/tree/master/accel/ane) does not seem realistic; probably 1340 MHz with 256 multipliers. That is closer to GPU. With A15+ I don't know whether it's higher clock or more multipliers. The cores are bigger on the die shot.

ANE Generation | FP16 Multipliers/Core | [TFLOPS](https://machinelearning.apple.com/research/neural-engine-transformers) | Clock |
-- | -- | -- | -- |
A11 | 128 | 0.6 | 1170 MHz |
A12 | 256 | 5.4 | 1320 MHz |
A14 | 256 | 11.66| 1422 MHz |
A15 | 256-384 | 15.8 | 1284-1932 MHz |
A16 | 256-384 | 17 | 1386-2076 MHz |

Hardware | Clock (MHz) | x mach_absolute_time
-- | -- | --
Mach Timebase | 24 | 1
A14 P-CPU | 3000 | 125
A14 P-CPU | 2892 | 120.5
A14 E-CPU | 1824 | 76
M1 Pro P-CPU | 3228 | 134.5
M1 Pro P-CPU | 3132 | 130.5
M1 Pro P-CPU | 3036 | 126.5
M1 Pro E-CPU | 2064 | 86
A15 P-CPU | 3240 | 135
A15 P-CPU | 3180 | 132.5
A15 E-CPU | 2016 | 84
A14 GPU | 1278 | 53.25
M1 Pro GPU | 1296 | 54
A15 GPU | 1338 | 55.75
M2 GPU | 1398 | 58.25

Date | Chip | P-CPU | E-CPU | GPU | ANE | RAM
-- | -- | -- | -- | -- | -- | --
Apr/3/2010 | A4 | 1000 |   | 200 |   | 200
Mar/11/2011 | A5 | 1000 |   | 200 |   | 400
Mar/16/2012 | A5X | 1000 |   | 266 |   | 400
Sep/21/2012 | A6 | 1300 |   | 266 |   | 533
Nov/2/2012 | A6X | 1400 |   | 300 |   | 533
Sep/20/2013 | A7 | 1400 |   | 450 |   | 800
Sep/19/2014 | A8 | 1500 |   | 533 |   | 800
Oct/22/2014 | A8X | 1500 |   | 533 |   | 800
Sep/25/2015 | A9 | 1850 |   | 650 |   | 1600
Nov/11/2015 | A9X | 2260 |   | 650 |   | 1600
Sep/16/2016 | A10 | 2340 | 1092 | 900 |   | 1600
Jun/13/2017 | A10X | 2380 | 1302 | 1000 |   | 1600
Sep/22/2017 | A11 | 2390 | 1692 | 1066 | 1170 | 2133
Sep/21/2018 | A12 | 2514 | 1590 | 1128 | 1320 | 2133
Nov/7/2018 | A12X | 2514 | 1590 | 1128 | 1320 | 2133
Sep/20/2019 | A13 | 2664 | 1728 | 1230 | 1320 | 2133
Oct/23/2020 | A14 | 3000 | 1824 | 1278 | 1422 | 2133
Nov/10/2020 | M1 | 3204 | 2064 | 1278 | 1422 | 2133
Sep/24/2021 | A15 | 3240 | 2016 | 1338 | 1932 | 2133
Oct/26/2021 | M1 Pro | 3228 | 2064 | 1296 | 1422 | 3200
Jun/24/2022 | M2 | 3504 | 2424 | 1398 | 1932 | 3200
Sep/7/2022 | A16 | 3474 | 2406 | 1398 | 2076 | 3200
Jan/17/2023 | M2 Pro | 3660 | 2424 | 1398 | 1932 | 3200
Sep/7/2024 |   |   |   |   |   | 4267

> Some A-series E-CPU stats may be inaccurate.

Graphs use upper estimate for ANE clock:

<img width="597" alt="Screenshot 2023-02-24 at 3 57 43 PM" src="https://user-images.githubusercontent.com/71743241/221290642-cd476069-ed08-4c19-8b90-0cd4400485da.png">

**Comment by geohot** [comment]
Probably right. Sadly Apple did new security updates and it got harder to call the ANE, so I stopped investigating.
