### ISSUE TITLE
CUDA casting error

### ISSUE THREAD

**Issue by ImanHosseini** [geohot/tinygrad#652]
Tried to test the CUDA runtime, here is t0.py:
```
from tinygrad.tensor import Tensor

x = Tensor.eye(256, requires_grad=True)
y = Tensor.eye(256, requires_grad=True)
z = y.matmul(x).sum()
z.backward()

print(x.grad.numpy())  # dz/dx
print(y.grad.numpy())  # dz/dy
```
And I run as:
```
CUDA=1 DEBUG=5 python3 t0.py
```
And I get:
[err.txt](https://github.com/geohot/tinygrad/files/10895149/err.txt)
The gist is:
```
kernel.cu(4): error: no suitable constructor exists to convert from "double" to "float4"
```
On this line:
```
 float4 acc0 = 0.0;
```
Which happens [here](https://github.com/geohot/tinygrad/blob/f028accae3ba365863d1522004fc07ee1d10d2e7/tinygrad/codegen/gpu.py#L224) or more specifically [here](https://github.com/geohot/tinygrad/blob/f028accae3ba365863d1522004fc07ee1d10d2e7/tinygrad/codegen/gpu.py#L63):
```
start_for_op : Final[Dict[Op, str]] = {ReduceOps.SUM: "0.0", ReduceOps.MAX: "-INFINITY"}
```

**Comment by ImanHosseini** [comment]
Oh sorry, just saw this unmerged PR which fixes this issue: https://github.com/geohot/tinygrad/pull/557/commits/4240514969cd0c438924c36d86695d5a8ac9d670
Closing this.

**Comment by geohot** [comment]
Woah, you are right, it's broken.

**Comment by geohot** [comment]
In general, feel free to keep issues open if they are reporting bugs in master. Should be fixed with https://github.com/geohot/tinygrad/commit/8c5dea8d72c6e565f5faa477cdcb10d63287212f
