### ISSUE TITLE
Feature request : MPS Backend from LiuLiu's codebase

### ISSUE THREAD

**Issue by brappier** [geohot/tinygrad#662]
Check out @liuliu 's NNC, maybe someone should use his mps backend in tinygrad. its much much faster and better written.

**Comment by brappier** [comment]
https://github.com/liuliu/s4nnc

**Comment by geohot** [comment]
Why is it faster? tinygrad should soon be able to saturate the hardware for common convs and matmuls, and for some models it's already generating the minimal number of kernels.

Minimum kernels + saturated reduces = max speed. Though the libnnc docs are neat to read, much better than tinygrad's.

**Comment by brappier** [comment]
Firstly, using BHWC is faster on apple hardware then BCWH. idk if tinygrad is using that. 
else idk, havent investigated it.

**Comment by geohot** [comment]
convs are implemented as HLOPs, even at the derivative layer there's no CONV. it's a quick change to use the other one.

**Comment by brappier** [comment]
Ill add some benchmarket scripts and send a PR maybe. But you can compare with NNC's stable diffusion on lowest end 8GB m1 mac. 

https://github.com/liuliu/swift-diffusion this literally runs for like 1.3sec per iteration with FP16 and 1.8 for FP32, tinygrad cannot compete with that. 

It could be the memory management.
