### ISSUE TITLE
LLaMA: AttributeError: type object 'CPUBuffer' has no attribute 'empty'

### ISSUE THREAD

**Issue by GrahamboJangles** [geohot/tinygrad#685]
```
python llama.py
cuda backend not available No module named 'pycuda'
metal backend not available No module named 'Metal'
using CPU backend
loaded weights in 692.08 ms, 0.00 GB loaded at 0.00 GB/s
Traceback (most recent call last):
  File "E:\Coding_and_Scripting\projects\LLaMA\llama tinygrad\llama.py", line 251, in <module>
    weights = fake_torch_load_zipped(open(WEIGHTS_FILENAME, "rb"), load_weights=getenv("WEIGHTS", 1), base_name="consolidated")
  File "E:\Coding_and_Scripting\projects\LLaMA\llama tinygrad\extra\utils.py", line 87, in fake_torch_load_zipped
    ret = my_unpickle(myfile)
  File "E:\Coding_and_Scripting\projects\LLaMA\llama tinygrad\extra\utils.py", line 79, in my_unpickle
    return MyPickle(fb0).load(), key_prelookup
  File "E:\Coding_and_Scripting\projects\LLaMA\llama tinygrad\extra\utils.py", line 43, in __new__
    ret = buffer.empty(args[2], dtype=storage_type)
AttributeError: type object 'CPUBuffer' has no attribute 'empty'
```

**Comment by geohot** [comment]
What branch are you on? That's not master

**Comment by GrahamboJangles** [comment]
> What branch are you on? That's not master

I don't know. I must've done something wrong. I re-cloned and reinstall tinygrad and now it works on CPU.

Can you point me in the right direction to get this working on an AMD GPU in Windows?

**Comment by geohot** [comment]
GPU=1 should just work (if you have 16GB+ of GPU ram)

**Comment by GrahamboJangles** [comment]
> GPU=1 should just work (if you have 16GB+ of GPU ram)

A batch script did it! Thank you Mr. Hots. 
Tinygrad has been the ONLY framework that has successfully run LLAMA at all on my PC.
I'll be sure to tell all my friends about it.

```bat
set GPU=1
python examples/llama.py```

**Comment by geohot** [comment]
not yet, but soon! I'll make the GPU the default if you have one.

**Comment by geohot** [comment]
if you `set OPTLOCAL=1` it should be 4x faster, at least it is on my AMD Radeon RX 6900 XT

**Comment by GrahamboJangles** [comment]
That is way faster. How can I contribute to the project?
