### ISSUE TITLE
LLaMA 13B not running on 32GB M1 

### ISSUE THREAD

**Issue by AlexAndrei98** [geohot/tinygrad#687]
Currently trying to run the 13B param but getting
```
alexandrei@Alexs-MBP-2 tinygrad % python3 examples/llama.py --personality george --large
using METAL backend
loaded weights in 0.37 ms, 0.00 GB loaded at 0.00 GB/s
Traceback (most recent call last):
  File "/Users/alexandrei/Projects/chat/tinygrad/examples/llama.py", line 206, in <module>
    weights0 = fake_torch_load_zipped(open(WEIGHTS0_FILENAME, "rb"), load_weights=getenv("WEIGHTS", 1), base_name="consolidated.00")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexandrei/Projects/chat/tinygrad/extra/utils.py", line 123, in fake_torch_load_zipped
    ret = my_unpickle(myfile)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/alexandrei/Projects/chat/tinygrad/extra/utils.py", line 85, in my_unpickle
    return MyPickle(fb0).load(), key_prelookup
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/alexandrei/Projects/chat/tinygrad/extra/utils.py", line 42, in __new__
    assert prod(args[2]) == obj_size
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

```

**Comment by geohot** [comment]
So I don't really have enough RAM to test it, it's bad for the SSD to swap.

if you can find a way to disable swap, I'll try it

**Comment by remixer-dec** [comment]
How did you manage to get METAL backend working? I installed PyOpenCL, but it still output "metal backend not available No module named 'Metal'" in llama branch, and now when it's merged,  all I see is:
<details><pre>Traceback (most recent call last):
  File "tinygrad/examples/llama.py", line 14, in <module>
    from tinygrad.lazy import Device
  File "tinygrad/tinygrad/lazy.py", line 22, in <module>
    Device = _Device()
  File "tinygrad/tinygrad/lazy.py", line 19, in __init__
    self.DEFAULT: str = functools.reduce(lambda val, ele: ele if getenv(ele) == 1 else val, self._buffers, "CPU")
  File "tinygrad/tinygrad/lazy.py", line 19, in <lambda>
    self.DEFAULT: str = functools.reduce(lambda val, ele: ele if getenv(ele) == 1 else val, self._buffers, "CPU")
  File "tinygrad/tinygrad/helpers.py", line 17, in getenv
    def getenv(key, default=0): return type(default)(os.getenv(key, default))
ValueError: invalid literal for int() with base 10: 'arm64-apple-darwin20.0.0-clang'</pre></details>

**Comment by geohot** [comment]
`pip3 install pyobjc-framework-Metal pyobjc-framework-Cocoa pyobjc-framework-libdispatch`

**Comment by remixer-dec** [comment]
@geohot thank you! 
It still crashed trying to get the CLANG environment variable as an integer `ValueError: invalid literal for int() with base 10: 'arm64-apple-darwin20.0.0-clang'`, but after removing it, it worked! The memory footprint is very impressive!

**Comment by python273** [comment]
llama 13B should work now, though using a lot of RAM

**Comment by python273** [comment]
mostly fixed RAM usage during weights concatenation in #710, though still peaks at 32G (previously was 50G)

#712 has saving of merged weights using `safetensors`, 13B loads much faster
