### ISSUE TITLE
Unify codegen/gpu.py and codegen/llvm.py with the Linearizer

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#695]
The Linearizer transforms ASTs into an array of "llops". It's a line, not a tree.

UnaryOps and BinaryOps can be used.

MemOps and LoopOps can also be used. 

This is where Token belongs. VariableOps for accumulator? Or maybe that's just Token from const.

Actually LoadOps from const doesn't seem like the worst op.

In Linearized space is a good place to think about memory coalescing too.

**Comment by geohot** [comment]
The runtimes should either be `InterpretedBuffer`or `Compiler`

Compiler has a staticmethod to create from a Linearized AST. import `CLikeCodegen`

**Comment by geohot** [comment]
In theory, the Linearizer can take in two LazyOps for fusion if they have the same dimensionality.

**Comment by martinloretzzz** [comment]
I can do the refactor of the llvm runtime. Current WIP is here: https://github.com/geohot/tinygrad/commit/9c02aaa7263ada415e9296bd7db47c8b65267e5a, I will continue tomorrow.
Got it kinda working, half of the tests pass, but there's still a lot to do.

**Comment by geohot** [comment]
Oh, I didn't see this, already did it!

If you are looking for something to do, the casting support is very basic.

https://github.com/geohot/tinygrad/issues/694
https://github.com/geohot/tinygrad/issues/693

I'm working on shapetracker stuff today
