### ISSUE TITLE
pip install "metal" issue ticket

### ISSUE THREAD

**Issue by u1npacker** [geohot/tinygrad#709]
pip install metal
Collecting metal
  Using cached metal-3.1.0.1.tar.gz (142 kB)
  Preparing metadata (setup.py) ... done
Collecting boto3
  Using cached boto3-1.26.94-py3-none-any.whl (135 kB)
Collecting pyaws>=0.1.18
  Using cached pyaws-0.4.1.tar.gz (29 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  │ exit code: 1
  ╰─> [4 lines of output]
      error in pyaws setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          awscli>=1.16.100boto3>=1.9.100
                ~~~~~~~~~~~^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details

**Comment by sohaiberrabii** [comment]
`pip install -e .'[metal]'` 😃

**Comment by u1npacker** [comment]
> pip install -e .'[metal]'

um same problem have it 

PS D:\Programming\LLaMA\tinygrad> pip install -e metal
ERROR: metal is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
PS D:\Programming\LLaMA\tinygrad> pip install -e .'[metal]'
ERROR: Invalid requirement: '[metal]'
PS D:\Programming\LLaMA\tinygrad> pip install -e . metal   
Obtaining file:///D:/Programming/LLaMA/tinygrad
  Preparing metadata (setup.py) ... done
Collecting metal
  Using cached metal-3.1.0.1.tar.gz (142 kB)
  Preparing metadata (setup.py) ... done
Collecting boto3
  Using cached boto3-1.26.94-py3-none-any.whl (135 kB)
Collecting pyaws>=0.1.18
  Using cached pyaws-0.4.1.tar.gz (29 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      error in pyaws setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          awscli>=1.16.100boto3>=1.9.100
                ~~~~~~~~~~~^
      Unable to locate awscli
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by dc-dc-dc** [comment]
seems like you are trying to install metal on windows, given that these libraries are objective-c wrappers and target macos frameworks I doubt they would work on windows.

**Comment by alecmerdler** [comment]
[Metal is for macOS](https://developer.apple.com/metal/), [not Windows](https://images7.memedroid.com/images/UPLOADED165/55a14cd3515b4.jpeg).

**Comment by BorderKeeper** [comment]
Same problem. I assume tinygrad will not work on Windows then since it needs metal. Although from tutorials it should work.

**Comment by dc-dc-dc** [comment]
To run on Windows you can use the following backends
- OpenCL
- CUDA(if you have a NVDIA card)
- CPU
- LLVM
- pytorch
