### ISSUE TITLE
./tinygrade/examples/llama.py editing TOKENIZER_FILENAME & Weights issues

### ISSUE THREAD

**Issue by kencom999** [geohot/tinygrad#717]
```
C:\BACKUP\tinygrad>cd C:\BACKUP\tinygrad
C:\BACKUP\tinygrad>set OPTLOCAL=1
C:\BACKUP\tinygrad>set GPU=1
C:\BACKUP\tinygrad>python examples/llama.py
using GPU backend
Traceback (most recent call last):
  File "C:\BACKUP\tinygrad\examples\llama.py", line 204, in <module>
    from sentencepiece import SentencePieceProcessor
ModuleNotFoundError: No module named 'sentencepiece'
C:\BACKUP\tinygrad>pause
Press any key to continue . . .
```
I'm not sure what this issue is...

**Comment by dc-dc-dc** [comment]
missing package sentencepiece
run `pip install sentencepiece`

**Comment by kencom999** [comment]
```
C:\Windows\System32>cd "C:\BACKUP\tinygrad"

C:\BACKUP\tinygrad>"C:\Users\Skygrass Chopper\AppData\Local\Programs\Python\Python39\python.exe" pip install sentencepiece
C:\Users\Skygrass Chopper\AppData\Local\Programs\Python\Python39\python.exe: can't open file 'C:\BACKUP\tinygrad\pip': [Errno 2] No such file or directory

C:\BACKUP\tinygrad>pip install sentencepiece
'pip' is not recognized as an internal or external command,
operable program or batch file.

C:\BACKUP\tinygrad>python pip install setencepiece
python: can't open file 'C:\BACKUP\tinygrad\pip': [Errno 2] No such file or directory
```

> missing package sentencepiece run `pip install sentencepiece`

I didn't add pip to path, not sure what this issue is again...

**Comment by dc-dc-dc** [comment]
The error is indicating that your just missing the sentencepiece module

`python -m pip install sentencepiece`

**Comment by kencom999** [comment]
Ok, got the sentence piece installed, now there's another error
```
C:\Windows\System32>cd "C:\BACKUP\tinygrad"

C:\BACKUP\tinygrad>set OPTLOCAL=1

C:\BACKUP\tinygrad>set GPU=1

C:\BACKUP\tinygrad>python examples/llama.py
using GPU backend
Traceback (most recent call last):
  File "C:\BACKUP\tinygrad\examples\llama.py", line 205, in <module>
    sp_model = SentencePieceProcessor(model_file=str(TOKENIZER_FILENAME))
  File "C:\Users\Skygrass Chopper\AppData\Local\Programs\Python\Python39\lib\site-packages\sentencepiece\__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "C:\Users\Skygrass Chopper\AppData\Local\Programs\Python\Python39\lib\site-packages\sentencepiece\__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "C:\Users\Skygrass Chopper\AppData\Local\Programs\Python\Python39\lib\site-packages\sentencepiece\__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
OSError: Not found: "C:\BACKUP\tinygrad\weights\LLaMA\tokenizer.model": No such file or directory Error #2
```

> The error is indicating that your just missing the sentencepiece module
> 
> `python -m pip install sentencepiece`

**Comment by elhumbertoz** [comment]
> Ok, got the sentence piece installed, now there's another error
> 
> ```
> C:\Windows\System32>cd "C:\BACKUP\tinygrad"
> 
> C:\BACKUP\tinygrad>set OPTLOCAL=1
> 
> C:\BACKUP\tinygrad>set GPU=1
> 
> C:\BACKUP\tinygrad>python examples/llama.py
> using GPU backend
> Traceback (most recent call last):
>   File "C:\BACKUP\tinygrad\examples\llama.py", line 205, in <module>
>     sp_model = SentencePieceProcessor(model_file=str(TOKENIZER_FILENAME))
>   File "C:\Users\Skygrass Chopper\AppData\Local\Programs\Python\Python39\lib\site-packages\sentencepiece\__init__.py", line 447, in Init
>     self.Load(model_file=model_file, model_proto=model_proto)
>   File "C:\Users\Skygrass Chopper\AppData\Local\Programs\Python\Python39\lib\site-packages\sentencepiece\__init__.py", line 905, in Load
>     return self.LoadFromFile(model_file)
>   File "C:\Users\Skygrass Chopper\AppData\Local\Programs\Python\Python39\lib\site-packages\sentencepiece\__init__.py", line 310, in LoadFromFile
>     return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
> OSError: Not found: "C:\BACKUP\tinygrad\weights\LLaMA\tokenizer.model": No such file or directory Error #2
> ```
> 
> > The error is indicating that your just missing the sentencepiece module
> > `python -m pip install sentencepiece`

+1
