### ISSUE TITLE
 pyopencl._cl.MemoryError: clEnqueueWriteBuffer failed: MEM_OBJECT_ALLOCATION_FAILURE,

### ISSUE THREAD

**Issue by mytitokpg** [geohot/tinygrad#722]
I'm running this hardware

Processor | Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Video Card | NVIDIA GeForce GTX 1660 Ti
Video Card #2 | Intel(R) UHD Graphics
Operating System | Windows 11
RAM | 64 GB

Chipset | NVIDIA GeForce GTX 1660 Ti
Manufacturer | Nvidia
Hardware T&L | Yes
Total Menmory | 38 GB
Dedicated Memory | 6.0 GB
Driver Version | 31.0.15.3118
Vertex Shader Version | 5.1
Pixel Shader Version | 5.1

and it's throwing this error. 

------------------------------
T:\TinyGrad\tinygrad>python examples/llama.py
using GPU backend
using <pyopencl.Device 'NVIDIA GeForce GTX 1660 Ti' on 'NVIDIA CUDA' at 0x1af146f39a0>
loading 117 ram used:  5.70 GB:  36%|█████████████████▍                              | 117/323 [00:04<00:08, 24.84it/s]
loaded weights in 4721.49 ms, 5.79 GB loaded at 1.23 GB/s
Traceback (most recent call last):
  File "T:\TinyGrad\tinygrad\examples\llama.py", line 263, in <module>
    weights = fake_torch_load_zipped(open(WEIGHTS_7B_FILENAME, "rb"), load_weights=getenv("WEIGHTS", 1))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "t:\tinygrad\tinygrad\extra\utils.py", line 151, in fake_torch_load_zipped
    load_weight(k,v)
  File "t:\tinygrad\tinygrad\extra\utils.py", line 138, in load_weight
    load_single_weight(v[2], myfile, v[3], v[4], v[0], v[5], mmap_allowed=True)
  File "t:\tinygrad\tinygrad\extra\utils.py", line 124, in load_single_weight
    t.realize()
  File "t:\tinygrad\tinygrad\tinygrad\tensor.py", line 88, in realize
    self.lazydata.realize()
  File "t:\tinygrad\tinygrad\tinygrad\lazy.py", line 114, in realize
    self.realized = Device[self.device].buffer.fromCPU(self.op.arg())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "t:\tinygrad\tinygrad\tinygrad\runtime\lib.py", line 28, in fromCPU
    ret._copyin(x)
  File "t:\tinygrad\tinygrad\tinygrad\runtime\ops_gpu.py", line 37, in _copyin
    cl.enqueue_copy(CL.cl_queue, self._buf, x, is_blocking=False)
  File "C:\Python311\Lib\site-packages\pyopencl\__init__.py", line 1936, in enqueue_copy
    return _cl._enqueue_write_buffer(queue, dest, src, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyopencl._cl.MemoryError: clEnqueueWriteBuffer failed: MEM_OBJECT_ALLOCATION_FAILURE

T:\TinyGrad\tinygrad>pause
Press any key to continue . . .
---------------------------------------------------

When I run nvidia-smi  I get this. . . 
--------------------------------------------------

C:\Users\tshol\Desktop>nvidia-smi
Mon Mar 20 20:23:19 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.29                 Driver Version: 531.29       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1660 Ti    WDDM | 00000000:01:00.0  On |                  N/A |
| N/A   39C    P0               22W /  N/A|    697MiB /  6144MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      6044    C+G   ...__8wekyb3d8bbwe\WindowsTerminal.exe    N/A      |
|    0   N/A  N/A     10684    C+G   ...CBS_cw5n1h2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A     11764    C+G   ...ogram Files\Pawns.app\Pawns.app.exe    N/A      |
|    0   N/A  N/A     12204    C+G   ...nt.CBS_cw5n1h2txyewy\SearchHost.exe    N/A      |
|    0   N/A  N/A     12596    C+G   ....4628.0_x64__8j3eq9eme6ctt\IGCC.exe    N/A      |
|    0   N/A  N/A     15136    C+G   ...2txyewy\StartMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A     15276    C+G   ...m Files (x86)\Overwolf\Overwolf.exe    N/A      |
|    0   N/A  N/A     16176    C+G   ...GeForce Experience\NVIDIA Share.exe    N/A      |
|    0   N/A  N/A     16904    C+G   C:\Windows\explorer.exe                   N/A      |
|    0   N/A  N/A     21560    C+G   ...pIntegrations\Grammarly.Desktop.exe    N/A      |
|    0   N/A  N/A     22200    C+G   ...e Stream\72.0.2.0\GoogleDriveFS.exe    N/A      |
|    0   N/A  N/A     22492    C+G   ...5n1h2txyewy\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A     24336    C+G   ....0_x64__kzh8wxbdkxb8p\DCv2\DCv2.exe    N/A      |
|    0   N/A  N/A     26180    C+G   ...rwolf\0.220.0.1\OverwolfBrowser.exe    N/A      |
|    0   N/A  N/A     26412    C+G   ...oogle\Chrome\Application\chrome.exe    N/A      |
+---------------------------------------------------------------------------------------+

I've got all dependencies installed and updated, graphics drivers updated, uninstalled and reinstalled PyOpenCL. 

Any help or guidance is greatly appreciated.

**Comment by mytitokpg** [comment]
> You are running out of memory on your GPU. See #704.

Can I set the .bat file differently and force it to use my CPU and RAM instead?

I tried
set OPTLOCAL=1
set GPU=0
python examples/llama.py
pause

But it tried using my GPU anyways.

**Comment by mytitokpg** [comment]
Is there a way to get it to use my CPU instead of GPU in the .bat file I'm using, or elsewhere. 

set OPTLOCAL=1
set GPU=1
python examples/llama.py
pause

I tried setting GPU to 0 and didn't work. 

I can get the models to run and use my CPU/RAM **_**using another method**_**. I'm just new to the tinygrad method, on seeing if it can give me a different output. 

The method I'm currently using with my CPU/RAM, I get an output, but it's not that great. So was trying to see if I can do the same with TinyGrad, could I get a better response. Any help is greatly appreciated.

**Comment by alextomskras** [comment]
> Is there a way to get it to use my CPU instead of GPU in the .bat file I'm using, or elsewhere in tinygrad's file structure?
> 
> My current start batch file for tinygrad. set OPTLOCAL=1 set GPU=1 python examples/llama.py pause
> 
> I tried setting GPU to 0 and didn't work.
> 
> I can get the models to run and use my CPU/RAM **_**using another method**_**. I'm just new to the tinygrad method, on seeing if it can give me a different output.
> 
> The method I'm currently using with my CPU/RAM, I get an output, but it's not that great. So was trying to see if I can do the same with TinyGrad, could I get a better response. Any help is greatly appreciated.

Please to try:

set CPU=1

and waiting 2 hour's may be or not)))
I'm try and continue to waiting 
(using CPU backend                                                                                                                                               loading 288 ram used: 13.48 GB: 100%|████████████████████████████████████████████████████████████████████████████████████████| 323/323 [00:31<00:00, 10.12it/s] loaded weights in 31934.20 ms, 13.48 GB loaded at 0.42 GB/s                                                                                                     Preparing KV cache for chatbot with personality Stacy... )

**Comment by mytitokpg** [comment]
I could never get mine working using TinyGrad even with the CPU setting. 

I could only get it running using a completely different package where you can set your own GPU setting. I can run even 30b on it, but responses take a while, 7b runs pretty good especially with using good LoRAs. 

OTHER COMPLETELY DIFFERENT PACKAGE LOADING AND GPU MEMORY SETTING
----------------------------------------------------------------------
Auto-assiging --gpu-memory 5 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████| 33/33 [00:10<00:00,  3.22it/s]
Loaded the model in 10.72 seconds.
----------------------------------------------------------------------

Just closing this issue though as I don't want to mention the completely different package and seem like I'm advertising the other package that did work for me with limited GPU hardware, inside the TinyGrad thread, and closing it. 

I do want to mention that the CPU fix in another comment did allow me to load the 7b model in TInyGrad, but it never let me do  anything else. But with the other completely different package than TinyGrad I am able to have full conversations with 7b, 13b, and 30b along with the 4bit builds, which I also needed the pytorch versions of all models aswell, which I got all from huggingface, to run successfully on my low GPU spec system.  

So for all low spec GPU systems, there is a way for you to run it, you just have to find it.
