### ISSUE TITLE
C Backend for training on embedded devices

### ISSUE THREAD

**Issue by benmkw** [geohot/tinygrad#735]
Does backpropagation/ training already work with the c backend/ any backend? I talked to some people who have interest in such things. e.g. https://github.com/Fraunhofer-IMS/AIfES_for_Arduino I personally think you mostly would want to do training offline but for some scenarios training on embedded devices seems to be desirable as well.

I think it should work and is probably just a matter of writing an example?

**Comment by geohot** [comment]
Yea it should work, the backend has no idea if it's doing a backward or forward pass.
