### ISSUE TITLE
Use tokens as the 'tiny' metric instead of lines

### ISSUE THREAD

**Issue by langfield** [geohot/tinygrad#743]
The current state of things is goofy. Your lines are long as heck because you promised to keep things under 1000 lines. That's obviously cheating, and SLoC is a bad metric anyway. Better to set an upper bound on the number of tokens, as counted by Python's `tokenize`.

If you want to put an upper bound on code complexity, use units which can't be "stuffed" with extra complexity.

**Comment by geohot** [comment]
Want to add this metric to `sz.sh`?
