### ISSUE TITLE
any todo on Separable Convs after Conv2D is done?

### ISSUE THREAD

**Issue by kartik4949** [geohot/tinygrad#75]
@geohot we can get that speeeed!

**Comment by geohot** [comment]
That's already supported with the groups argument!

**Comment by kartik4949** [comment]
@geohot
im talking about depthwise convolution which are 7x less params than normal. 
 https://towardsdatascience.com/a-basic-introduction-to-separable-convolutions-b99ec3102728

depthwise separable conv -> depthwise conv + point wise conv
