### ISSUE TITLE
[Not a bug] Warning for Python 3.9.0 

### ISSUE THREAD

**Issue by RakibFiha** [geohot/tinygrad#76]
As mentioned in `setup.py` tinygrad requires > python 3.8
Pytorch installation fails on python3.9.0. So, `tinygrad` examples will not work for Python 3.9.0

See: https://github.com/pytorch/pytorch/issues/47354 for more details.

I am using Python 3.8.6 and it is working fine but was not able to install requirements.txt due to `torch` and `torchvision` on Python 3.9.0 most possibly because in PyPI there are no wheels, ready to install binaries, for Python 3.9 as its still quite new.

**Comment by harshrathod50** [comment]
I wonder why torch is not forwards compatible with Python? Only selected versions are supported. 🤨

**Comment by geohot** [comment]
Nothing actionable here. Use Python 3.8!

**Comment by marcelbischoff** [comment]
Now works under 3.9!?!

**Comment by RakibFiha** [comment]
> Now works under 3.9!?!

@marcelbischoff Just tried to install `tinygrad` now in python3.9.1 but failed with exit status 1.

Installation on Python3.8.6 worked fine.
