### ISSUE TITLE
cannot import name 'fetch'' from tinygrads.utils'

### ISSUE THREAD

**Issue by LordMero** [geohot/tinygrad#77]
When installing via pip, tinigrad.utils.fetch is different from the last commit. 
fp = os.path.join("/tmp", hashlib.md5(url.encode('utf-8')).hexdigest())
 s miising from pip version

**Comment by sencere** [comment]
I had the same error. First I used conda env to install python38, I installed all the dependencies and then I moved efficientnet.py out of example in the main folder and it worked.

**Comment by LordMero** [comment]
Yeah just cloned and copied over the package location. Weird though

**Comment by LordMero** [comment]
That’s because there seem to be an error in the code installed by pip: fp
line is missing
