### ISSUE TITLE
Winograd FLOPS

### ISSUE THREAD

**Issue by philipturner** [geohot/tinygrad#781]
Some comments mentioned that MPSGraph convolutions used Winograd. Could there be documentation of exactly how much FLOPS? Anything over 8.49 TFLOPS is not physically possible.

https://github.com/geohot/tinygrad/blob/master/extra/gemm/metal_conv.py#L11-L14

**Comment by geohot** [comment]
How do you get 8.49? My metal matmul gets 8.48, are you saying more isn't possible for some reason?

**Comment by philipturner** [comment]
I've never seem MPSGraph FP32 matrix multiplication exceed 80% ALU. It would align with the MATMUL<8x8xF32> instruction taking 20 cycles, which I stated in the uarch docs. However, I'm starting to doubt whether this is true - perhaps the instructions to read from device memory even out to 2 cycles, and MATMUL<8x8xF32> takes 18.

**Comment by geohot** [comment]
I think if you remove the memory accesses you can get them all.

**Comment by philipturner** [comment]
I can probably test that in metal-benchmarks, but never got around to it. All SIMD permutes have a 2-cycle penalty, so 18 cycles sounds right. There’s just a register bandwidth bottleneck, making FP16 slightly faster than FP32.

**Comment by hemangjoshi37a** [comment]
Hello @geohot, @philipturner, In order to shed light on the actual FLOPS performance, I think it would be beneficial to implement some sort of monitoring or profiling mechanism that can accurately measure the FLOPS. This could give us a more in-depth understanding of the performance details when using Winograd convolutions or MPSGraph.

Here is a simple Python script that can be adapted to measure FLOPS in a function, this might give us a starting point:

```python
import time
import numpy as np

def measure_flops(func, *args, **kwargs):
    start_time = time.time()
    res = func(*args, **kwargs)
    end_time = time.time()
    flops = res.size / (end_time - start_time)
    return flops
```

**Comment by philipturner** [comment]
The better thing to do, is run multiple trials in quick succession. Then, report the maximum value of all the trials. I would think this is not some novel functionality, but standard practice - you should _already_ be doing it, if you report any numbers in FLOPS.

**Comment by philipturner** [comment]
Just thought I might post this. Apple is using Winograd, but the GEMM part is so inefficient, it's almost no better than decent ConvGEMM.

<img width="407" alt="Screenshot 2023-06-20 at 8 08 18 PM" src="https://github.com/geohot/tinygrad/assets/71743241/e7e9c864-591c-4734-b33b-9b7fd7e6b1d5">

<img width="370" alt="Screenshot 2023-06-20 at 9 50 46 PM" src="https://github.com/geohot/tinygrad/assets/71743241/52ca1e22-838e-4b7c-9e10-df4c518a3348">

<img width="375" alt="Screenshot 2023-06-20 at 9 50 10 PM" src="https://github.com/geohot/tinygrad/assets/71743241/04215390-e627-4202-850a-292b35ef3fea">
