### ISSUE TITLE
.parameters() for nn classes

### ISSUE THREAD

**Issue by Cheapshot003** [geohot/tinygrad#7895]
Hi! Has anybody thought about adding a .parameters() method to the [nn](https://github.com/tinygrad/tinygrad/blob/master/tinygrad/nn/__init__.py) things that returns all the parameters of the module in a list. That way I can just make a list of all parameters in a model by unpacking the list that gets returned of every .parameters() call. [PyTorch](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.parameters) does it that way.

**Comment by chenyuxyz** [comment]
use `get_parameters`
