### ISSUE TITLE
TinyGrad core for respecting 1K loc limit

### ISSUE THREAD

**Issue by maderix** [geohot/tinygrad#84]
How about separating the core (tensor, ops, opsgpu, nn, utils etc.) logic into tiny-grad core project and creating another repo for extensions (models, examples, notebooks,  etc.) IMO core code should be high quality(lol) but complete.

**Comment by geohot** [comment]
Only the "tinygrad" dir counts toward that limit. examples and tests don't.

**Comment by maderix** [comment]
cool thanks!
