### ISSUE TITLE
Conditions for obtaining training mission bounties

### ISSUE THREAD

**Issue by shjwudp** [geohot/tinygrad#845]
May I ask a question? What are the conditions for getting training mission bounties? Do I need to compare with a particular baseline, or do I just prove that the loss of the model is decreasing reasonably? If the former, what baselines should I compare against?

**Comment by wozeparrot** [comment]
We are looking at the mlperf benchmarks here: https://mlcommons.org/en/training-normal-21/

There are specified quality targets that needs to be hit for each of the benchmarks.

More info can found in the reference implementations: https://github.com/mlcommons/training/

**Comment by geohot** [comment]
You must give me instructions to reproduce training a model using tinygrad that hits the MLPerf target quality within 12 hours on any reasonable hardware I can buy or rent.

**Comment by shjwudp** [comment]
@wozeparrot @geohot Thank you! mlperf is indeed a reasonable condition, with some difficulty. Thanks for the answer. It's clear to me now.
