### ISSUE TITLE
any of these touchups interesting?

### ISSUE THREAD

**Issue by smurfd** [geohot/tinygrad#871]
Hey
I have thought about a few things, no idea if you find them interesting

1) What `prepare.sh` is this? could be nice to have a link to it https://github.com/geohot/tinygrad/blob/0fc4cf72a2261fff7ef432ed9eb9bd003459dcd9/datasets/imagenet.py#L1

2) Would it be ok to add a check if this json exists, if not provide a link to the json file as error message?
https://github.com/geohot/tinygrad/blob/0fc4cf72a2261fff7ef432ed9eb9bd003459dcd9/datasets/imagenet.py#L9
should be this one, right, but then maby as a raw link `https://github.com/raghakot/keras-vis/blob/master/resources/imagenet_class_index.json`
It would be someting like:
```
ci = json.load(open(BASEDIR / "imagenet_class_index.json"))
```
turns into:
```
if not os.path.isfile(BASEDIR / "imagenet_class_index.json"): print("Get .json from https://path.to/file.json and put in datasets/imagenet/"); exit()
ci = json.load(open(BASEDIR / "imagenet_class_index.json"))
```

3) The test `test_multistep_adamw_high_lr` in `test/test_optim.py` fails unless you use `CPU=1` or `GPU=1` on my M1
ok to add, or are we happy that it fails and try to fix the error? :
```
@unittest.skipUnless(Device.DEFAULT in ["CPU", "GPU"], "needs CPU=1 or GPU=1")
def test_multistep_adamw_high_lr(self): self._test_adamw(10, {'lr': 10}, 1e-5, 3e-4)
```

4) Could be nice to have a list of environment variables you can set to change things when you run tinygrad, in something like `docs/abstraction.py`
```
CPU=1 # Use CPU
GPU=1 # Use GPU
METAL=1 # Use Mac Metal backend
LLVM=1 # Use LLVM backend
DEBUG=1-4 # Set debug output level
...
```

**Comment by geohot** [comment]
Really this needs a built in imagenet downloader.

3. Why is the test broken? Should be fixed, not masked.

4. I'd merge nice docs that explain all the env vars.

**Comment by wozeparrot** [comment]
Re 3: is this METAL being weird again?
@smurfd can you see if the test is broken for you on TORCH, LLVM, and CLANG?

We really should have METAL in ci but github actions doesn't allow gpu usage yet...

**Comment by wozeparrot** [comment]
> @wozeparrot so it seems for python v3.8.16 it breaks, for 3.8.13 (which is default for MacOS) it works with CLANG, LLVM and TORCH it also works for 3.8.16 tried python 3.10.9 works aswell without any environment variables.

That's really strange, I don't have a mac to test this myself, but maybe just increasing the tolerances a bit would work? What is it failing with?

Re imagenet: I used: https://gist.github.com/antoinebrl/7d00d5cb6c95ef194c737392ef7e476a

**Comment by smurfd** [comment]
thanks for the imagenet link, 
i think we can ignore the error. i suspect wrongly pyenv installed python v3.8.16

**Comment by smurfd** [comment]
Closing this issue, after realizing it was user error causing my error.
Created a PR for docs & now a PR for imagenet downloader
