### ISSUE TITLE
ggml support

### ISSUE THREAD

**Issue by felrock** [geohot/tinygrad#878]
Is there any plan to support [ggml](https://github.com/ggerganov/ggml) models?

**Comment by python273** [comment]
what do you mean by it exactly?

**Comment by felrock** [comment]
I was thinking along the lines of loading/storing models in ggml format.

**Comment by python273** [comment]
afaik ggml files are just weights, the model is C code calling the library. So making weights loader is likely not hard, but the actual model has to be reimplemented

**Comment by python273** [comment]
hmm, ggml can export computational graphs now (not for all models it seems), so might be actually possible:
https://github.com/ggerganov/ggml/pull/108

**Comment by geohot** [comment]
We use safetensors as a standard on disk format
