### ISSUE TITLE
Standard tinygrad weight format?

### ISSUE THREAD

**Issue by wozeparrot** [geohot/tinygrad#882]
Inspired by #878 and kinda needed for mlperf training? not sure if mlperf specifies the checkpoint format.

We might want to look into having a standardized way of storing model weights and the code to read and write them.

I'm not sure what the best way to go about this is, for example in https://github.com/wozeparrot/tinyrwkv I'm just pickling the state_dict converted to ndarrays. The thing is the ML community seems to be moving away from pickle due to its possible security concerns during weight loading.

Maybe we adopt [safetensors](https://github.com/huggingface/safetensors)? But safetensors is pretty big and has a rust dependency which seems like way too much stuff to bring in.

Thoughts?

**Comment by geohot** [comment]
Disktensors! I think we just convert the state_dict to a bunch of disktensors in a folder, then for distribution, you can tar.xz that folder.

**Comment by wozeparrot** [comment]
Right! I totally forgot that you implemented those :facepalm:

Need a good way to load them tho `Tensor.empty(*shape, device='disk:/tmp/file')` doesn't seem very scalable to the entire state_dict.

Do we need metadata with the format?

**Comment by geohot** [comment]
Yea, and I don't have a great way to do that. An option I was playing with was putting the dtype and shape in the file extension, but I don't love that.

Maybe metadata is just json concatted to the end of the file that describes the tensor(s) in it.

**Comment by wozeparrot** [comment]
> then for distribution, you can tar.xz that folder.

I don't know if this would actually be good, because it means that we can no longer mmap the tensors directly and have to have a step of extracting them first.

I do quite like safetensors tho, It would be nice if we could find a way to make it work with disktensors or at least incorporate parts of it.

**Comment by geohot** [comment]
Oh safe tensors sound good. Re: working with disktensors. Add a "@<start>-<end>" to the filename to get only that region?

**Comment by wozeparrot** [comment]
Doesn't look like there are compliance tests, closest I could find are the tests in the reference rust library: https://github.com/huggingface/safetensors/blob/main/safetensors/src/tensor.rs

**Comment by geohot** [comment]
Ugh, cast isn't exactly what I want...

```
t = Tensor.empty(1, dtype=dtypes.int64, device=f"disk:{fn}").numpy()[0]
j = Tensor.empty(8+int(t), dtype=dtypes.uint8, device=f"disk:{fn}")[8:]
print(json.loads(j.numpy().tobytes()))
```

**Comment by geohot** [comment]
Quick prototype: https://github.com/geohot/tinygrad/pull/903

**Comment by geohot** [comment]
Safetensors was merged, that's the standard.

**Comment by felrock** [comment]
We made it guys! https://github.com/tinygrad/tinygrad/pull/7046
