### ISSUE TITLE
float64 support

### ISSUE THREAD

**Issue by eichenroth** [geohot/tinygrad#891]
Support for float64 over all plattforms.
This would also fix up to 20 ONNX tests.

Is there a plan to add this? Otherwise there is no way to fully support ONNX, since some tests are hard relying on that.

**Comment by dc-dc-dc** [comment]
Metal currently does not support float64 / double

**Comment by geohot** [comment]
Would merge PR to skip those tests. float64 is not in scope for tinygrad.

**Comment by eichenroth** [comment]
You did not :-D
There are just 20 random tests in the ONNX test suite that require float64. To me its surprising, that we only have 20, since all operations support float64s.

I fear that tinygrad needs a better engineered version of the ONNX test suite to cover the parts tinygrad supports and ignores the others.

In any case we should close this issue, since it cannot be resolved.

**Comment by geohot** [comment]
That PR didn't make it clear that those tests needed float64. Idk, if they are really needed, maybe we should support it, at least on some backends.
