### ISSUE TITLE
Currently at 989 lines. Reduce lines while improving readability!

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#94]
Remember, this isn't code golf. The goal is to make the code easier to maintain. In general that's also smaller, but smaller that's harder to maintain can't be merged.

**Comment by marcelbischoff** [comment]
Maybe a stupid idea. But once there are stable OpenCL implementations we could ditch the numpy ones, since OpenCL runs on the CPU as well?!?

**Comment by geohot** [comment]
I think we'll keep both, forces the Tensor class to remain good and generic. And it doesn't really hurt complexity, they are totally separate files.

**Comment by geohot** [comment]
Down at 941 now, even with the 40 line profiler.

**Comment by geohot** [comment]
At 927 without the GPU backward conv. Going to be close once we merge it. Almost feature complete!

**Comment by geohot** [comment]
978

**Comment by kartik4949** [comment]
ops.py Class Pad2d - line 103, # return statement can be oneline.

**Comment by big-c-note** [comment]
What lines are we counting, anything in the tindygrad folder? Any line length guidelines/style guidelines?

**Comment by kartik4949** [comment]
@big-c-note look one of PR's test checks there should be lines details

**Comment by tcapelle** [comment]
i would recommend a fastai coding style for readability and low line count.

**Comment by EvanSchalton** [comment]
#212 shaves off another ~55 lines

**Comment by geohot** [comment]
Down to 937!
