### ISSUE TITLE
PyOpenCL doesn't work in GitHub actions

### ISSUE THREAD

**Issue by geohot** [geohot/tinygrad#95]
Fix so we can test GPU ops

**Comment by ryanneph** [comment]
CI tests on GPU likely requires self-hosted runners: https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners

**Comment by geohot** [comment]
CPU OpenCL would be fine too.

**Comment by geohot** [comment]
pocl was the answer

**Comment by ryanneph** [comment]
Nice work
