### ISSUE TITLE
CLANG on windows errors when running clang command

### ISSUE THREAD

**Issue by dc-dc-dc** [geohot/tinygrad#981]
When trying to run the CLANG runtime on windows I get an error when building the lib.

The issues stems from [here](https://github.com/geohot/tinygrad/blob/2d567ef688473734cd21f31ae9344d06d01d6ec4/tinygrad/runtime/ops_clang.py#LL13C11-L13C11)  as this is building a shared library for the unix system with os specific flags.

From some quick testing the two flags in question are
- fPIC (I think for windows this is already enabled by default if its a shared library)
- lm (attempting to link the math lib but on windows its named something else?)

Also saw that ctypes has some flags for windows which may play a factor here as well

**Comment by geohot** [comment]
Should be fixed with #986!
